import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    es: {
        dashboard: 'Dashboard',
        finances: 'Mis Finanzas',
        categories: 'Categorías',
        goals: 'Metas',
        last_movements: 'Últimos movimientos',
        all_day: 'Todo el día',
        reports: 'Análisis Patrimonial',
        strategic_analysis: 'Análisis Patrimonial',
        strategic_goals: 'Metas Estratégicas',
        wealth_evolution: 'Evolución del Patrimonio',
        monthly_comparison: 'Comparativa Mensual',
        update_progress: 'Actualizar Avance',
        cumulative_balance: 'Saldo de la Cuenta',
        budgets: 'Presupuestos',
        ai_assistant: 'Asistente IA',
        settings: 'Configuración',
        profile: 'Perfil',
        logout: 'Cerrar Sesión',
        account_type: 'Básica',
        notifications: 'Notificaciones',
        terminal_id: 'ID DE TERMINAL',
        operational_status: 'Estado Operacional: ÓPTIMO',
        system_ok: 'SISTEMA: OK',
        db_connected: 'BD: CONECTADA',
        save: 'Guardar',
        cancel: 'Cancelar',
        language: 'Idioma',
        select_language: 'Seleccionar Idioma',
        spanish: 'Español',
        english: 'Inglés',
        // Dashboard
        welcome: '¡Hola de nuevo!',
        total_balance: 'Balance Total',
        monthly_income: 'Ingresos del Mes',
        monthly_expenses: 'Gastos del Mes',
        recent_movements: 'Movimientos Recientes',
        view_all: 'Ver todo',
        engineering_card: 'Agenda Financiera',
        smart_tracking_system: 'SISTEMA DE SEGUIMIENTO INTELIGENTE',
        budget_allocation: 'Distribución de Presupuestos',
        survival_engine: 'Motor de Supervivencia',
        safe_daily_rate: 'Tasa Higiénica de Gasto',
        per_day: 'por día',
        buffer_time_label: 'Tiempo de Amortiguación',
        financial_health: 'Salud Financiera',
        // Engineering Assistant
        smart_timeline: 'Línea de Tiempo Inteligente',
        next_events: 'Próximos Eventos',
        no_events: 'No hay eventos próximos',
        financial_metrics: 'Métricas de Ingeniería',
        monthly_reminder: 'Recordatorio Mensual',
        delete_event_confirm: '¿Eliminar este evento de la agenda?',
        recurring_event: 'Evento Recurrente',
        payment_day: 'Día de Pago',
        deadline_day: 'Día Límite',
        next_payment: 'Próximo Pago',
        deadline_approaching: '¡Límite de pago cerca!',
        delete_action: 'Eliminar',
        keep_action: 'Mantener',
        not_paid_yet: 'Aún no pagado',
        already_paid: 'Pagado este mes',
        priority_optional: 'Opcional',
        priority_important: 'Importante',
        priority_critical: 'Crítico',
        add_event: 'Añadir Evento',
        event_title: 'Título del Evento',
        event_title_placeholder: 'Ej: Cumpleaños de Mamá',
        priority_label: 'Prioridad',
        // Recordatorios & Eventos
        edit_event: 'Editar Evento',
        save_changes: 'Guardar Cambios',
        schedule_manual_event: 'Agendar Evento Manual',
        add_to_timeline: 'Añadir a Línea de Tiempo',
        monthly_suggested: 'Sugerencia de ahorro mensual',
        income: 'Ingresos',
        expenses: 'Gastos',
        balance: 'Balance',
        monthly_summary: 'Resumen del Mes',
        uncategorized: 'Sin Categoría',
        progress: 'Progreso',
        target_date: 'Fecha objetivo',
        target_amount: 'Monto Objetivo',
        current_amount: 'Monto Actual',
        deadline: 'Fecha Límite',
        add_goal: 'Agregar Meta',
        edit_goal: 'Editar Meta',
        suggested_savings: 'Ahorro Sugerido',
        // Categories
        add_category: 'Nueva Categoría',
        edit_category: 'Editar Categoría',
        category_name: 'Nombre de la Categoría',
        category_color: 'Color',
        search_categories: 'Buscar categorías...',
        delete_confirm: '¿Estás seguro de eliminar esto?',
        // Finance Summary
        total_income: 'Total Ingresos',
        total_expense: 'Total Gastos',
        net_balance: 'Balance Neto',
        export_csv: 'Exportar CSV',
        export_pdf: 'Exportar PDF',
        add_movement: 'Nuevo Movimiento',
        edit_movement: 'Editar Movimiento',
        filter_month: 'Este Mes',
        filter_last_month: 'Mes Pasado',
        filter_all: 'Todos',
        filter_custom: 'Personalizado',
        transactions: 'Transacciones',
        monthly_summary_card: 'Resumen del Mes',
        monthly_savings: 'Ahorro del Mes',
        most_spent_category: 'Categoría más Gastada',
        // Time
        morning: '¡Buenos días!',
        afternoon: '¡Buenas tardes!',
        evening: '¡Buenas noches!',
        // Dashboard (extra)
        amount_greater_than_zero: 'El monto debe ser mayor a 0',
        movement_registered: '¡Movimiento registrado correctamente!',
        registration_error: 'Error al registrar. Verifica los campos.',
        guest: 'Usuario',
        no_movements: 'Aún no tienes movimientos.',
        register_first: 'Registrar primero',
        today_label: 'Hoy',
        yesterday_label: 'Ayer',
        earlier_label: 'Ayer',
        no_description: 'Sin descripción',
        quick_registration: 'Registro Rápido',
        movement_type: 'Tipo de Movimiento',
        expense_label: 'Gasto',
        income_label: 'Ingreso',
        amount_label: 'Monto ($)',
        description_label: 'Descripción',
        description_placeholder: 'Ej: Café, Supermercado, Sueldo...',
        category_label: 'Categoría',
        select_category: 'Selecciona una categoría...',
        date_label: 'Fecha',
        saving: 'Guardando...',
        report_subtitle: 'Visión estratégica de tu salud financiera y crecimiento.',
        // ChatIA
        ai_welcome: '¡Hola! Soy tu **Asistente Financiero IA** potenciado por Gemini. Tengo acceso a tus datos financieros reales y puedo responder cualquier pregunta sobre tus ingresos, gastos, balance y más. ¿En qué te ayudo hoy?',
        typing: 'El asistente está pensando...',
        ask_question: 'Pregunta sobre tus finanzas...',
        ai_error: 'Lo siento, ocurrió un error al procesar tu pregunta. Intenta de nuevo.',
        ai_disclaimer: 'El Asistente IA puede cometer errores. Verifica datos importantes en Mis Finanzas.',
        connected_data: 'Conectado a tus datos',
        suggestion_1: '¿Cuánto he gastado en total?',
        suggestion_2: '¿Cuál es mi balance actual?',
        suggestion_3: '¿En qué categoría gasto más?',
        suggestion_4: '¿Cuánto he ahorrado?',
        suggestion_5: '¿Cuál es mi riesgo financiero?',
        suggestion_6: '¿Cuántos días me dura el dinero?',
        fallback_expense: 'Revisa la sección **"Mis Finanzas"** para ver el detalle de tus gastos.',
        fallback_income: 'Puedes ver tus ingresos totales en la sección **"Mis Finanzas"**.',
        fallback_balance: 'Tu balance se muestra en el **Dashboard** en la parte superior.',
        fallback_error: 'No pude conectarme al Asistente IA. Puedes ver todos tus datos financieros en **"Mis Finanzas"** y el **Dashboard**.',
        // Profile
        manage_info: 'Gestiona tu información personal',
        member_since: 'Miembro desde',
        full_name: 'Nombre Completo',
        email_address: 'Correo Electrónico',
        change_password: 'Cambiar Contraseña',
        new_password: 'Nueva Contraseña',
        confirm_password: 'Confirmar Contraseña',
        password_min: 'Mín. 6 caracteres',
        password_repeat: 'Repite la contraseña',
        passwords_dont_match: 'Las contraseñas no coinciden',
        password_help: 'Deja ambos campos vacíos para no cambiar la contraseña.',
        profile_updated: '¡Perfil actualizado correctamente!',
        profile_error: 'Error al actualizar el perfil.',
        // Login / Register / ForgotPassword
        login_title: 'Inicia sesión en tu cuenta',
        login_button: 'Ingresar',
        logging_in: 'Iniciando sesión...',
        no_account: '¿No tienes una cuenta?',
        register_here: 'Regístrate aquí',
        forgot_password_q: '¿Olvidaste tu contraseña?',
        register_title: 'Crea una cuenta nueva',
        register_button: 'Regístrate',
        creating_account: 'Creando cuenta...',
        have_account: '¿Ya tienes una cuenta?',
        login_here: 'Inicia sesión',
        recovery_title: 'Recuperar Contraseña',
        recovery_desc: 'Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.',
        recovery_email_sent: '¡Correo enviado!',
        recovery_instr: 'Hemos enviado un enlace de recuperación a: ',
        recovery_button: 'Enviar enlace de recuperación',
        sending: 'Enviando...',
        back_to_login: 'Volver al inicio de sesión',
        main_navigation: 'Navegación principal',
        close_menu: 'Cerrar menú',
        // Elite Login Specific
        start_session: 'Iniciar Sesión',
        welcome_elite: 'Bienvenido',
        create_account_elite: 'Crea tu Cuenta',
        recover_elite: 'Recuperar',
        manage_future: 'Gestiona tu futuro hoy',
        join_elite: 'Únete a la elite financiera',
        forgot_pwd_q_elite: '¿Olvidaste tu contraseña?',
        register_action: 'Registrarse',
        next_step: 'Siguiente Paso',
        back_to_login_elite: 'Volver al Login',
        recover_desc_elite: 'Introduce tu correo para recibir un enlace de recuperación.',
        send_link: 'Enviar Enlace',
        interact: 'Interactuar',
        vs_previous_month: 'vs mes pasado',
        close_notification: 'Cerrar notificación',
        category_deleted: 'Categoría eliminada.',
        category_delete_error: 'Error al eliminar. La categoría puede tener movimientos asociados.',
        category_name_required: 'El nombre es obligatorio.',
        category_updated: '¡Categoría actualizada!',
        category_created: '¡Categoría creada!',
        custom_color: 'Color personalizado',
        category_delete_warning: 'Esto puede afectar los movimientos asociados a esta categoría.',
        error_loading_goals: 'Error cargando metas:',
        goal_updated: '¡Meta actualizada!',
        goal_created: '¡Meta creada con éxito!',
        goal_save_error: 'Error al guardar la meta. Revisa los datos.',
        goal_deleted: 'Meta eliminada.',
        goal_delete_error: 'Error al eliminar la meta.',
        invalid_amount: 'Ingresa un monto válido.',
        progress_updated: '¡Avance actualizado!',
        progress_error: 'Error al actualizar el avance.',
        active_label: 'activa',
        actives_label: 'activas',
        completed_label_sm: 'completada',
        completed_labels_sm: 'completadas',
        expired_label_sm: 'Vencida',
        deadline_label: 'Límite',
        goal_completed_title: 'META COMPLETADA',
        no_goals_yet: 'Sin metas aún',
        create_first_goal: 'Crear mi primera meta',
        goal_name_label: 'Nombre de la Meta',
        update_progress: 'Actualizar Avance',
        update_button: 'Actualizar',
        // Common
        risk_low: 'BAJO',
        risk_medium: 'MEDIO',
        risk_critical: 'CRÍTICO',
        loading: 'Cargando...',
        error_loading: 'Error al cargar los datos',
        no_data: 'No hay datos disponibles',
        // Reports
        key_metrics: 'Métricas Clave',
        net_balance_report: 'Balance Neto',
        projected_savings: 'Ahorro Proyectado',
        reserve_days: 'Días de Reserva',
        expenses_by_category: 'Gastos por Categoría',
        cash_flow_evolution: 'Evolución de Flujo',
        max_income: 'Ingreso Máximo',
        max_expense: 'Gasto Máximo',
        daily_avg: 'Promedio Diario',
        risk_level_label: 'Nivel de Riesgo',
        no_expenses_recorded: 'Sin gastos registrados',
        movement_history: 'Historial de Movimientos',
        income_vs_expense_day: 'Ingresos vs Gastos por Día',
        expense_distribution: 'Distribución de Gastos',
        reports_subtitle: "Análisis técnico de tus movimientos",
        executive_summary: "RESUMEN EJECUTIVO DE CARTERA",
        daily_burn_rate: "TASA DE QUEMADO DIARIO",
        // PDF / Exports
        pdf_report_title: 'Reporte Financiero',
        pdf_generated_at: 'Generado el',
        pdf_summary_title: 'Resumen del Período',
        total_expense: 'Gastos Totales',
        percentage_label: '% DE GASTOS',
        pdf_net_balance: 'Balance Neto',
        pdf_income: 'Ingresos Totales',
        pdf_expense: 'Gastos Totales',
        pdf_negative: '(Negativo)',
        pdf_movements_title: 'Movimientos Detallados',
        pdf_page: 'Página',
        pdf_of: 'de',
        pdf_footer: 'MenteBillete Core - Reporte de Inteligencia Financiera',
        generating_pdf: 'Generando PDF...',
        exporting_tx: 'Exportando movimientos...',
        no_tx_export: 'No hay transacciones para exportar',
        // Presupuestos
        of_the_month: 'del Mes',
        budget_saved: 'Presupuesto guardado',
        save_error: 'Error al guardar',
        delete_budget_confirm: '¿Eliminar este límite de presupuesto?',
        budget_deleted: 'Presupuesto eliminado',
        delete_error: 'Error al eliminar',
        configuring_limits: 'Configurando límites financieros...',
        control_spending: 'Controla cuánto quieres gastar por categoría cada mes',
        global_budget: 'Presupuesto Global (Mensual)',
        available: 'Disponible',
        budget_alert: 'ALERTA: Has superado el 90% de tu presupuesto este mes.',
        define_limit: 'Definir Límite',
        select_placeholder: 'Seleccionar...',
        monthly_limit_label: 'Límite Mensual ($)',
        assign_limit: 'ASIGNAR LÍMITE',
        budget_help: 'Los presupuestos te ayudan a no gastar de más. Recibirás alertas visuales cuando te acerques al límite.',
        no_budgets_title: 'Aún no has definido límites mensuales.',
        no_budgets_subtitle: 'Empieza seleccionando una categoría a la izquierda.',
        limit_prefix: 'Límite: ',
        spent_prefix: 'Gastado: ',
        // Configuracion
        lang_changed_en: 'Idioma cambiado a Inglés',
        lang_changed_es: 'Idioma cambiado a Español',
        settings_desc: 'Gestiona tus preferencias de cuenta y aplicación.',
        security: 'Seguridad',
        lang_help: '* Cambiar el idioma afectará a todos los menús y etiquetas principales de la aplicación.',
        dark_mode: 'Modo Oscuro',
        light_mode: 'Modo Claro',
        appearance: 'Apariencia',
        // Categorias
        movement_updated: 'Movimiento actualizado',
        // Seguridad y Notificaciones
        password_current: 'Contraseña Actual',
        password_new: 'Nueva Contraseña',
        password_confirm: 'Confirmar Contraseña',
        password_changed: 'Contraseña actualizada correctamente',
        notif_budget_exceed: 'Alertas de límite de presupuesto',
        notif_new_login: 'Alertas de nuevos inicios de sesión',
        notif_weekly_report: 'Resumen semanal por correo',
        notif_ai_tips: 'Consejos de ahorro de la IA',
        notif_updated: 'Preferencias de notificación actualizadas',
        no_notifications: 'No hay notificaciones pendientes',
        clear_all: 'Limpiar todo',
        recent_activity: 'Actividad Reciente',
        // Evolución Línea de Tiempo
        goal_milestone_title: 'HITO DE META ALCANZADO',
        goal_milestone_desc: 'Has alcanzado el {percentage}% de tu meta: {name}. ¡Sigue así!',
        savings_challenge_title: 'RETO DE FIN DE SEMANA',
        savings_challenge_desc: 'Mantén tus gastos hormiga en $0 por las próximas 48 horas.',
        sub_reminder_title: 'SUSCRIPCIÓN PRÓXIMA',
        sub_reminder_desc: 'Se detectó un cargo recurrente para {name} en los próximos días.',
        discipline_streak_title: 'RACHA DE DISCIPLINA',
        discipline_streak_desc: 'Has estado bajo tu presupuesto diario por {days} días seguidos. 🏆',
        invest_alert_title: 'OPORTUNIDAD DE INVERSIÓN',
        invest_alert_desc: 'Tu balance es sólido. Considera mover ${amount} a tu fondo de ahorro/inversión.',
        balance_forecast_title: 'PRONÓSTICO DE CIERRE',
        balance_forecast_desc: 'Saldo proyectado al final del mes: ${amount}.',
        days_streak: 'días',
        hide_challenges: 'Ocultar Retos de Ahorro',
        hide_forecasts: 'Ocultar Pronóstico Mensual',
        timeline_settings: 'Ajustes de Línea de Tiempo',
        show_challenges: 'Mostrar retos de ahorro sugeridos por la IA',
        show_forecasts: 'Mostrar proyecciones de saldo a fin de mes',
        expenses_section: 'Gastos',
        income_section: 'Ingresos',
        category_type: 'Tipo de Categoría',
        system_category_no_edit: 'Esta categoría es del sistema y no se puede modificar.',
        starting_system: 'Iniciando Sistema...',
        organize_finances: 'Organiza y visualiza tus ingresos y gastos',
        no_custom_categories: 'Sin categorizar',
        no_category: 'Sin Categoría',
        delete_warning: 'Esta acción no se puede deshacer.',
        pdf_subtitle: 'SISTEMA TRANSACCIONAL PATRIMONIAL',
        pdf_hash: 'HASH DE INTEGRIDAD',
        pdf_footer_msg: 'REPORTE GENERADO MEDIANTE PROTOCOLO ELITE MENTE BILLETE',
        pdf_page_cert: 'CERTIFICADO DIGITAL PAG',
        pdf_filename_prefix: 'AUDITORIA_ELITE_',
        pdf_audit_title: 'AUDITORÍA',
        csv_filename_prefix: 'AUDITORIA_',
        actions_label: 'Acciones',
        edit_label: 'Editar',
        delete_label: 'Eliminar',
        search_placeholder: 'Buscar...',
        clear_search: 'Limpiar búsqueda',
        no_results_search: 'No hay resultados para la búsqueda',
        period_label: 'Período:',
        from_label: 'Desde',
        to_label: 'Hasta',
        register_to_see: 'Registra un gasto para visualizar',
        no_expenses_cat: 'No hay gastos registrados en este período',
        movement_deleted: 'Movimiento eliminado correctamente',
        filter_week: 'Últimos 7 días',
        filter_30_days: 'Últimos 30 días',
    },
    en: {
        dashboard: 'Dashboard',
        finances: 'My Finances',
        categories: 'Categories',
        goals: 'Goals',
        last_movements: 'Last movements',
        all_day: 'All day',
        reports: 'Wealth Analysis',
        strategic_analysis: 'Wealth Analysis',
        strategic_goals: 'Strategic Goals',
        wealth_evolution: 'Wealth Evolution',
        monthly_comparison: 'Monthly Comparison',
        update_progress: 'Update Progress',
        cumulative_balance: 'Account Balance',
        budgets: 'Budgets',
        ai_assistant: 'AI Assistant',
        settings: 'Settings',
        profile: 'Profile',
        logout: 'Logout',
        account_type: 'Basic',
        notifications: 'Notifications',
        terminal_id: 'TERMINAL ID',
        operational_status: 'Operational Status: OPTIMAL',
        system_ok: 'SYSTEM: OK',
        db_connected: 'DB: CONNECTED',
        save: 'Save',
        cancel: 'Cancel',
        language: 'Language',
        select_language: 'Select Language',
        spanish: 'Spanish',
        english: 'English',
        // Dashboard
        welcome: 'Welcome back!',
        total_balance: 'Total Balance',
        monthly_income: 'Monthly Income',
        monthly_expenses: 'Monthly Expenses',
        recent_movements: 'Recent Movements',
        view_all: 'View all',
        engineering_card: 'Financial Agenda',
        smart_tracking_system: 'SMART TRACKING SYSTEM',
        budget_allocation: 'Budget Allocation',
        survival_engine: 'Survival Engine',
        safe_daily_rate: 'Safe Daily Spending Rate',
        per_day: 'per day',
        buffer_time_label: 'Buffer Time',
        financial_health: 'Financial Health',
        // Engineering Assistant
        smart_timeline: 'Smart Timeline',
        next_events: 'Next Events',
        no_events: 'No upcoming events',
        financial_metrics: 'Engineering Metrics',
        monthly_reminder: 'Monthly Reminder',
        days: 'days',
        delete_event_confirm: 'Delete this event from the agenda?',
        recurring_event: 'Recurring Event',
        payment_day: 'Payment Day',
        deadline_day: 'Deadline Day',
        next_payment: 'Next Payment',
        deadline_approaching: 'Deadline approaching!',
        delete_action: 'Delete',
        keep_action: 'Keep',
        not_paid_yet: 'Not paid yet',
        already_paid: 'Paid this month',
        priority_optional: 'Optional',
        priority_important: 'Important',
        priority_critical: 'Critical',
        add_event: 'Add Event',
        event_title: 'Event Title',
        event_title_placeholder: 'E.g., Mom\'s Birthday',
        priority_label: 'Priority',
        // Recordatorios & Eventos
        edit_event: 'Edit Event',
        save_changes: 'Save Changes',
        schedule_manual_event: 'Schedule Manual Event',
        add_to_timeline: 'Add to Timeline',
        monthly_suggested: 'Monthly suggested savings',
        income: 'Income',
        expenses: 'Expenses',
        balance: 'Balance',
        monthly_summary: 'Monthly Summary',
        uncategorized: 'Uncategorized',
        progress: 'Progress',
        target_date: 'Target date',
        target_amount: 'Target Amount',
        current_amount: 'Current Amount',
        deadline: 'Deadline',
        add_goal: 'Add Goal',
        edit_goal: 'Edit Goal',
        suggested_savings: 'Suggested Savings',
        // Categories
        add_category: 'New Category',
        edit_category: 'Edit Category',
        category_name: 'Category Name',
        category_color: 'Color',
        search_categories: 'Search categories...',
        delete_confirm: 'Are you sure you want to delete this?',
        // Finance Summary
        total_income: 'Total Income',
        total_expense: 'Total Expenses',
        net_balance: 'Net Balance',
        export_csv: 'Export CSV',
        add_movement: 'New Movement',
        edit_movement: 'Edit Movement',
        filter_month: 'This Month',
        filter_last_month: 'Last Month',
        filter_all: 'All',
        filter_custom: 'Custom Range',
        transactions: 'Transactions',
        monthly_summary_card: 'Monthly Summary',
        monthly_savings: 'Monthly Savings',
        most_spent_category: 'Most Spent Category',
        // Time
        morning: 'Good morning!',
        afternoon: 'Good afternoon!',
        evening: 'Good evening!',
        // Dashboard (extra)
        amount_greater_than_zero: 'Amount must be greater than 0',
        movement_registered: 'Movement registered successfully!',
        registration_error: 'Registration error. Check the fields.',
        guest: 'User',
        no_movements: 'You don\'t have any movements yet.',
        register_first: 'Register first',
        today_label: 'Today',
        yesterday_label: 'Yesterday',
        earlier_label: 'Yesterday',
        no_description: 'No description',
        quick_registration: 'Quick Registration',
        movement_type: 'Movement Type',
        expense_label: 'Expense',
        income_label: 'Income',
        amount_label: 'Amount ($)',
        description_label: 'Description',
        description_placeholder: 'E.g.: Coffee, Supermarket, Salary...',
        category_label: 'Category',
        select_category: 'Select a category...',
        date_label: 'Date',
        saving: 'Saving...',
        report_subtitle: 'Strategic vision of your financial health and growth.',
        // ChatIA
        ai_welcome: 'Hello! I am your **AI Financial Assistant** powered by Gemini. I have access to your real financial data and can answer any questions about your income, expenses, balance, and more. How can I help you today?',
        typing: 'The assistant is thinking...',
        ask_question: 'Ask about your finances...',
        ai_error: 'Sorry, an error occurred while processing your question. Try again.',
        ai_disclaimer: 'The AI Assistant can make mistakes. Verify important data in My Finances.',
        connected_data: 'Connected to your data',
        suggestion_1: 'How much have I spent in total?',
        suggestion_2: 'What is my current balance?',
        suggestion_3: 'In which category do I spend the most?',
        suggestion_4: 'How much have I saved?',
        suggestion_5: 'What is my financial risk?',
        suggestion_6: 'How many days does my money last?',
        fallback_expense: 'Check the **"My Finances"** section to see your expense details.',
        fallback_income: 'You can see your total income in the **"My Finances"** section.',
        fallback_balance: 'Your balance is shown on the **Dashboard** at the top.',
        fallback_error: 'I couldn\'t connect to the AI Assistant. You can see all your financial data in **"My Finances"** and the **Dashboard**.',
        // Profile
        manage_info: 'Manage your personal information',
        member_since: 'Member since',
        full_name: 'Full Name',
        email_address: 'Email Address',
        change_password: 'Change Password',
        new_password: 'New Password',
        confirm_password: 'Confirm Password',
        password_min: 'Min. 6 characters',
        password_repeat: 'Repeat the password',
        passwords_dont_match: 'Passwords don\'t match',
        password_help: 'Leave both fields empty to not change the password.',
        profile_updated: 'Profile updated successfully!',
        profile_error: 'Error updating profile.',
        // Login / Register / ForgotPassword
        login_title: 'Log in to your account',
        login_button: 'Log in',
        logging_in: 'Logging in...',
        no_account: 'Don\'t have an account?',
        register_here: 'Register here',
        forgot_password_q: 'Forgot your password?',
        register_title: 'Create a new account',
        register_button: 'Register',
        creating_account: 'Creating account...',
        have_account: 'Already have an account?',
        login_here: 'Log in',
        recovery_title: 'Recover Password',
        recovery_desc: 'Enter your email and we will send you a link to reset your password.',
        recovery_email_sent: 'Email sent!',
        recovery_instr: 'We have sent a recovery link to: ',
        recovery_button: 'Send recovery link',
        sending: 'Sending...',
        back_to_login: 'Back to login',
        main_navigation: 'Main navigation',
        close_menu: 'Close menu',
        // Elite Login Specific
        start_session: 'Start Session',
        welcome_elite: 'Welcome',
        create_account_elite: 'Create Account',
        recover_elite: 'Recover',
        manage_future: 'Manage your future today',
        join_elite: 'Join the financial elite',
        forgot_pwd_q_elite: 'Forgot your password?',
        register_action: 'Register',
        next_step: 'Next Step',
        back_to_login_elite: 'Back to Login',
        recover_desc_elite: 'Enter your email to receive a recovery link.',
        send_link: 'Send Link',
        interact: 'Interact',
        vs_previous_month: 'vs previous month',
        close_notification: 'Close notification',
        category_deleted: 'Category deleted.',
        category_delete_error: 'Error deleting. The category may have associated movements.',
        category_name_required: 'Name is required.',
        category_updated: 'Category updated!',
        category_created: 'Category created!',
        category_error: 'Error saving category.',
        error_loading_goals: 'Error loading goals:',
        goal_updated: 'Goal updated!',
        goal_created: 'Goal created successfully!',
        goal_save_error: 'Error saving goal. Check the data.',
        goal_deleted: 'Goal deleted.',
        goal_delete_error: 'Error deleting goal.',
        invalid_amount: 'Enter a valid amount.',
        progress_updated: 'Progress updated!',
        progress_error: 'Error updating progress.',
        active_label: 'active',
        actives_label: 'active',
        completed_label_sm: 'completed',
        completed_labels_sm: 'completed',
        expired_label_sm: 'Expired',
        deadline_label: 'Deadline',
        goal_completed_title: 'GOAL COMPLETED',
        no_goals_yet: 'No goals yet',
        create_first_goal: 'Create first goal',
        goal_name_label: 'Goal Name',
        update_progress: 'Update Progress',
        update_button: 'Update',
        // Common
        risk_low: 'LOW',
        risk_medium: 'MEDIUM',
        risk_critical: 'CRITICAL',
        loading: 'Loading...',
        error_loading: 'Error loading data',
        no_data: 'No data available',
        // Reports
        key_metrics: 'Key Metrics',
        net_balance_report: 'Net Balance',
        projected_savings: 'Projected Savings',
        reserve_days: 'Reserve Days',
        expenses_by_category: 'Expenses by Category',
        cash_flow_evolution: 'Cash Flow Evolution',
        max_income: 'Max Income',
        max_expense: 'Max Expense',
        daily_avg: 'Daily Avg',
        risk_level_label: 'Risk Level',
        no_expenses_recorded: 'No expenses recorded',
        movement_history: 'Movement History',
        income_vs_expense_day: 'Income vs Expense per Day',
        expense_distribution: 'Expense Distribution',
        reports_subtitle: "Technical analysis of your movements",
        executive_summary: "EXECUTIVE PORTFOLIO SUMMARY",
        daily_burn_rate: "DAILY BURN RATE",
        // PDF / Exports
        export_pdf: "Export PDF",
        total_expense: 'Total Expenses',
        percentage_label: '% OF EXPENSES',
        budget_saved: 'Budget saved',
        save_error: 'Error saving',
        delete_budget_confirm: 'Delete this budget limit?',
        budget_deleted: 'Budget deleted',
        delete_error: 'Error deleting',
        configuring_limits: 'Configuring financial limits...',
        control_spending: 'Control how much you want to spend per category each month',
        global_budget: 'Global Budget (Monthly)',
        available: 'Available',
        budget_alert: 'ALERT: You have exceeded 90% of your budget this month.',
        define_limit: 'Define Limit',
        select_placeholder: 'Select...',
        monthly_limit_label: 'Monthly Limit ($)',
        assign_limit: 'ASSIGN LIMIT',
        budget_help: 'Budgets help you avoid overspending. You will receive visual alerts when you approach the limit.',
        no_budgets_title: 'No monthly limits defined yet.',
        no_budgets_subtitle: 'Start by selecting a category on the left.',
        limit_prefix: 'Limit: ',
        spent_prefix: 'Spent: ',
        // Configuracion
        lang_changed_en: 'Language changed to English',
        lang_changed_es: 'Idioma cambiado a Español',
        settings_desc: 'Manage your account and application preferences.',
        security: 'Security',
        lang_help: '* Changing the language will affect all major menus and labels of the application.',
        dark_mode: 'Dark Mode',
        light_mode: 'Light Mode',
        appearance: 'Appearance',
        // Categorias
        movement_updated: 'Movement updated',
        // Security & Notifications
        password_current: 'Current Password',
        password_new: 'New Password',
        password_confirm: 'Confirm Password',
        password_changed: 'Password updated successfully',
        notif_budget_exceed: 'Budget limit alerts',
        notif_new_login: 'New login alerts',
        notif_weekly_report: 'Weekly email summary',
        notif_ai_tips: 'AI saving tips',
        notif_updated: 'Notification preferences updated',
        no_notifications: 'No pending notifications',
        clear_all: 'Clear all',
        recent_activity: 'Recent Activity',
        // Profile
        personal_details: 'Personal Details',
        financial_snapshot: 'Financial Snapshot',
        account_security: 'Account Security',
        phone_number: 'Phone Number',
        bio: 'Bio',
        verified_account: 'Verified Account',
        security_status: 'Security Status',
        high: 'High',
        medium: 'Medium',
        low_label: 'Low',
        last_sync: 'Last Sync',
        activity_overview: 'Activity Overview',
        // Timeline Evolution
        goal_milestone_title: 'GOAL MILESTONE REACHED',
        goal_milestone_desc: 'You have reached {percentage}% of your goal: {name}. Keep going!',
        savings_challenge_title: 'WEEKEND CHALLENGE',
        savings_challenge_desc: 'Keep your impulse spending at $0 for the next 48 hours.',
        sub_reminder_title: 'UPCOMING SUBSCRIPTION',
        sub_reminder_desc: 'A recurring charge for {name} was detected in the coming days.',
        discipline_streak_title: 'DISCIPLINE STREAK',
        discipline_streak_desc: 'You have been under your daily budget for {days} days straight. 🏆',
        invest_alert_title: 'INVESTMENT OPPORTUNITY',
        invest_alert_desc: 'Your balance is solid. Consider moving ${amount} to your savings/investment fund.',
        balance_forecast_title: 'MONTH-END FORECAST',
        balance_forecast_desc: 'Projected balance at the end of the month: ${amount}.',
        days_streak: 'days',
        hide_challenges: 'Hide Savings Challenges',
        hide_forecasts: 'Hide Monthly Forecast',
        timeline_settings: 'Timeline Settings',
        show_challenges: 'Show AI-suggested savings challenges',
        show_forecasts: 'Show month-end balance projections',
        expenses_section: 'Expenses',
        income_section: 'Income',
        category_type: 'Category Type',
        system_category_no_edit: 'This is a system category and cannot be modified.',
        starting_system: 'Starting System...',
        organize_finances: 'Organize and visualize your income and expenses',
        no_custom_categories: 'Uncategorized',
        no_category: 'No Category',
        delete_warning: 'This action cannot be undone.',
        pdf_subtitle: 'TRANSACTIONAL WEALTH SYSTEM',
        pdf_hash: 'INTEGRITY HASH',
        pdf_footer_msg: 'REPORT GENERATED VIA MENTE BILLETE ELITE PROTOCOL',
        pdf_page_cert: 'DIGITAL CERTIFICATE PAG',
        pdf_filename_prefix: 'ELITE_AUDIT_',
        pdf_audit_title: 'AUDIT',
        csv_filename_prefix: 'AUDIT_',
        actions_label: 'Actions',
        edit_label: 'Edit',
        delete_label: 'Delete',
        search_placeholder: 'Search...',
        clear_search: 'Clear search',
        no_results_search: 'No results found',
        period_label: 'Period:',
        from_label: 'From',
        to_label: 'To',
        register_to_see: 'Register an expense to see data',
        no_expenses_cat: 'No expenses recorded in this period',
        movement_deleted: 'Movement deleted successfully',
        filter_week: 'Last 7 days',
        filter_30_days: 'Last 30 days',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'es');

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => (prev === 'es' ? 'en' : 'es'));
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
