import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    es: {
        dashboard: 'Dashboard',
        finances: 'Mis Finanzas',
        categories: 'Categorías',
        goals: 'Metas',
        ai_assistant: 'Asistente IA',
        settings: 'Configuración',
        profile: 'Perfil',
        logout: 'Cerrar Sesión',
        account_type: 'Básica',
        notifications: 'Notificaciones',
        terminal_id: 'ID DE TERMINAL',
        operational_status: 'Estado Operacional: ÓPTIMO',
        system_ok: 'SISTEMA: OK',
        db_connected: 'BD: CONECTADA',
        save: 'Guardar',
        cancel: 'Cancelar',
        language: 'Idioma',
        select_language: 'Seleccionar Idioma',
        spanish: 'Español',
        english: 'Inglés',
        // Dashboard
        welcome: '¡Hola de nuevo!',
        total_balance: 'Balance Total',
        monthly_income: 'Ingresos del Mes',
        monthly_expenses: 'Gastos del Mes',
        recent_movements: 'Movimientos Recientes',
        view_all: 'Ver todo',
        engineering_card: 'Tarjeta Financiera de Ingeniería',
        // Stats
        efficiency: 'Eficiencia',
        savings_rate: 'Tasa de Ahorro',
        financial_health: 'Salud Financiera',
        // Engineering Assistant
        smart_timeline: 'Línea de Tiempo Inteligente',
        next_events: 'Próximos Eventos',
        no_events: 'No hay eventos próximos',
        financial_metrics: 'Métricas de Ingeniería',
        // Goals
        monthly_suggested: 'Sugerencia de ahorro mensual',
        progress: 'Progreso',
        target_date: 'Fecha objetivo',
        target_amount: 'Monto Objetivo',
        current_amount: 'Monto Actual',
        deadline: 'Fecha Límite',
        add_goal: 'Agregar Meta',
        edit_goal: 'Editar Meta',
        suggested_savings: 'Ahorro Sugerido',
        // Categories
        add_category: 'Nueva Categoría',
        edit_category: 'Editar Categoría',
        category_name: 'Nombre de la Categoría',
        category_color: 'Color',
        search_categories: 'Buscar categorías...',
        delete_confirm: '¿Estás seguro de eliminar esto?',
        // Finance Summary
        total_income: 'Total Ingresos',
        total_expense: 'Total Gastos',
        net_balance: 'Balance Neto',
        export_csv: 'Exportar CSV',
        export_pdf: 'Exportar PDF',
        filter_month: 'Este Mes',
        filter_last_month: 'Mes Pasado',
        filter_custom: 'Personalizado',
        transactions: 'Transacciones',
        // Time
        morning: '¡Buenos días!',
        afternoon: '¡Buenas tardes!',
        evening: '¡Buenas noches!',
        // Dashboard (extra)
        amount_greater_than_zero: 'El monto debe ser mayor a 0',
        movement_registered: '¡Movimiento registrado correctamente!',
        registration_error: 'Error al registrar. Verifica los campos.',
        guest: 'Usuario',
        no_movements: 'Aún no tienes movimientos.',
        register_first: 'Registrar primero',
        no_description: 'Sin descripción',
        quick_registration: 'Registro Rápido',
        movement_type: 'Tipo de Movimiento',
        expense_label: '💸 Gasto',
        income_label: '💰 Ingreso',
        amount_label: 'Monto ($)',
        description_label: 'Descripción',
        description_placeholder: 'Ej: Café, Supermercado, Sueldo...',
        category_label: 'Categoría',
        select_category: 'Selecciona una categoría...',
        date_label: 'Fecha',
        saving: 'Guardando...',
        // ChatIA
        ai_welcome: '¡Hola! Soy tu **Asistente Financiero IA** potenciado por Gemini. Tengo acceso a tus datos financieros reales y puedo responder cualquier pregunta sobre tus ingresos, gastos, balance y más. ¿En qué te ayudo hoy?',
        typing: 'El asistente está pensando...',
        ask_question: 'Pregunta sobre tus finanzas...',
        ai_error: 'Lo siento, ocurrió un error al procesar tu pregunta. Intenta de nuevo.',
        ai_disclaimer: 'El Asistente IA puede cometer errores. Verifica datos importantes en Mis Finanzas.',
        connected_data: 'Conectado a tus datos',
        suggestion_1: '¿Cuánto he gastado en total?',
        suggestion_2: '¿Cuál es mi balance actual?',
        suggestion_3: '¿En qué categoría gasto más?',
        suggestion_4: '¿Cuánto he ahorrado?',
        suggestion_5: '¿Cuál es mi riesgo financiero?',
        suggestion_6: '¿Cuántos días me dura el dinero?',
        fallback_expense: 'Revisa la sección **"Mis Finanzas"** para ver el detalle de tus gastos.',
        fallback_income: 'Puedes ver tus ingresos totales en la sección **"Mis Finanzas"**.',
        fallback_balance: 'Tu balance se muestra en el **Dashboard** en la parte superior.',
        fallback_error: 'No pude conectarme al Asistente IA. Puedes ver todos tus datos financieros en **"Mis Finanzas"** y el **Dashboard**.',
        // Profile
        manage_info: 'Gestiona tu información personal',
        member_since: 'Miembro desde',
        full_name: 'Nombre Completo',
        email_address: 'Correo Electrónico',
        change_password: 'Cambiar Contraseña',
        new_password: 'Nueva Contraseña',
        confirm_password: 'Confirmar Contraseña',
        password_min: 'Mín. 6 caracteres',
        password_repeat: 'Repite la contraseña',
        passwords_dont_match: 'Las contraseñas no coinciden',
        password_help: 'Deja ambos campos vacíos para no cambiar la contraseña.',
        profile_updated: '¡Perfil actualizado correctamente!',
        profile_error: 'Error al actualizar el perfil.',
        // Login / Register / ForgotPassword
        login_title: 'Inicia sesión en tu cuenta',
        login_button: 'Ingresar',
        logging_in: 'Iniciando sesión...',
        no_account: '¿No tienes una cuenta?',
        register_here: 'Regístrate aquí',
        forgot_password_q: '¿Olvidaste tu contraseña?',
        register_title: 'Crea una cuenta nueva',
        register_button: 'Regístrate',
        creating_account: 'Creando cuenta...',
        have_account: '¿Ya tienes una cuenta?',
        login_here: 'Inicia sesión',
        recovery_title: 'Recuperar Contraseña',
        recovery_desc: 'Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.',
        recovery_email_sent: '¡Correo enviado!',
        recovery_instr: 'Hemos enviado un enlace de recuperación a: ',
        recovery_button: 'Enviar enlace de recuperación',
        sending: 'Enviando...',
        back_to_login: 'Volver al inicio de sesión',
        // EngineeringAssistant
        critical: 'CRÍTICO',
        important: 'IMPORTANTE',
        optional: 'OPCIONAL',
        delete_event_confirm: '¿Eliminar este evento de la línea de tiempo?',
        goal_prefix: 'Meta: ',
        expired_label: 'VENCIDO',
        today_label: 'HOY',
        for_label: 'PARA',
        missing_amount: 'Faltan ',
        to_complete: ' para completar.',
        recurrent_expense_prefix: 'Gasto Recurrente: ',
        projected: 'PROYECTADO',
        recurrent_suggestion: 'Patrón de gasto detectado. Sugerencia: programar apartado.',
        monthly_deficit: 'Déficit Mensual',
        alert: 'ALERTA',
        overspend_desc: 'Tus gastos superan tus ingresos este mes.',
        critical_buffer: 'Reserva Crítica',
        low_buffer_desc: 'Buffer inferior a 30 días',
        remaining_days_label: 'días restantes',
        past_label: 'PASADO',
        event_label: 'EVENTO: ',
        manual_event_desc: 'Evento manual registrado por el usuario.',
        survival_engine: 'Motor de Supervivencia',
        safe_daily_rate: 'TASA DE GASTO DIARIO SEGURO',
        per_day: '/ DÍA',
        buffer_time_label: 'TIEMPO DE BUFFER',
        days: 'Días',
        low_risk: 'BAJO',
        set_asides_month: 'Apartados (Mes Actual)',
        view_movements: 'VER MOVIMIENTOS',
        no_expenses_month: 'Sin gastos registrados este mes.',
        strategic_goals: 'Metas Estratégicas',
        schedule: 'PROGRAMAR',
        no_active_goals: 'No hay metas activas.',
        add_event: 'AGREGAR EVENTO',
        optimize: 'OPTIMIZAR',
        schedule_manual_event: 'PROGRAMAR EVENTO MANUAL',
        event_title: 'Título del Evento',
        event_title_placeholder: 'Ej: Pago de Renta, Mantenimiento, etc.',
        amount_optional: 'Monto (Opcional)',
        priority_label: 'Prioridad',
        priority_important: 'IMPORTANTE',
        priority_critical: 'CRÍTICO / URGENTE',
        priority_optional: 'OPCIONAL / RECORDATORIO',
        add_to_timeline: 'AGREGAR A LA LÍNEA',
        vs_previous_month: 'vs mes anterior',
        close_notification: 'Cerrar notificación',
        category_deleted: 'Categoría eliminada.',
        category_delete_error: 'Error al eliminar. La categoría puede tener movimientos asociados.',
        category_name_required: 'El nombre es obligatorio.',
        category_updated: '¡Categoría actualizada!',
        category_created: '¡Categoría creada!',
        category_error: 'Error al guardar la categoría.',
        organize_finances: 'Organiza tus gastos e ingresos',
        category_label: 'categoría',
        categories_label: 'categorías',
        category_color: 'Color de categoría',
        edit_label: 'Editar',
        delete_label: 'Eliminar',
        no_results_for: 'Sin resultados para',
        no_custom_categories: 'Sin categorías personalizadas',
        categories_help: 'Las categorías te ayudan a organizar tus ingresos y gastos',
        preview: 'Vista previa...',
        category_name: 'Nombre de la categoría',
        custom_color: 'Color personalizado',
        category_delete_warning: 'Esto puede afectar los movimientos asociados a esta categoría.',
        error_loading_goals: 'Error cargando metas:',
        goal_updated: '¡Meta actualizada!',
        goal_created: '¡Meta creada con éxito!',
        goal_save_error: 'Error al guardar la meta. Revisa los datos.',
        goal_deleted: 'Meta eliminada.',
        goal_delete_error: 'Error al eliminar la meta.',
        invalid_amount: 'Ingresa un monto válido.',
        progress_updated: '¡Avance actualizado!',
        progress_error: 'Error al actualizar el avance.',
        active_label: 'activa',
        actives_label: 'activas',
        completed_label_sm: 'completada',
        completed_labels_sm: 'completadas',
        expired_label_sm: 'Vencida',
        deadline_label: 'Límite',
        goal_completed_title: 'META COMPLETADA',
        no_goals_yet: 'Sin metas aún',
        create_first_goal: 'Crear mi primera meta',
        goal_name_label: 'Nombre de la Meta',
        update_progress: 'Actualizar Avance',
        update_button: 'Actualizar',
        // Common
        risk_low: 'BAJO',
        risk_medium: 'MEDIO',
        risk_critical: 'CRÍTICO',
        loading: 'Cargando...',
        error_loading: 'Error al cargar los datos',
        no_data: 'No hay datos disponibles',
        pdf_report_title: 'Reporte de Movimientos Financieros',
        pdf_net_balance: 'Balance Neto',
        pdf_income: 'Ingresos Totales',
        pdf_expense: 'Gastos Totales',
        pdf_negative: '(Negativo)',
        pdf_why_title: '¿Por qué PDF y no captura de pantalla?',
        pdf_v1: '✓ Texto seleccionable y buscable (Ctrl+F)',
        pdf_v2: '✓ Imprime en tamaño A4/carta con resolución perfecta',
        pdf_v3: '✓ Comparte o archiva oficialmente sin pérdida de calidad',
        pdf_v4: '✓ Funciona en cualquier lector de PDF (celular, computadora, tablet)',
        no_results_search: 'No se encontraron movimientos con los filtros actuales.',
        no_expenses_cat: 'Sin gastos por categoría este mes',
        register_to_see: 'Registra tus primeros gastos para ver el análisis',
        from_label: 'Desde',
        to_label: 'Hasta',
        period_label: 'Periodo:',
        no_category: 'Sin Cat.',
        actions_label: 'Acciones',
        filter_all: 'Todos',
        evolution_title: 'Evolución Temporal',
        clear_search: 'Limpiar búsqueda',
        pdf_generated_at: 'Generado',
        pdf_summary_title: 'Resumen del Período',
        pdf_movements_title: 'Movimientos',
        pdf_page: 'Página',
        pdf_of: 'de',
        pdf_footer: 'MenteBillete — Tu Asistente Financiero Inteligente'
    },
    en: {
        dashboard: 'Dashboard',
        finances: 'My Finances',
        categories: 'Categories',
        goals: 'Goals',
        ai_assistant: 'AI Assistant',
        settings: 'Settings',
        profile: 'Profile',
        logout: 'Logout',
        account_type: 'Basic',
        notifications: 'Notifications',
        terminal_id: 'TERMINAL ID',
        operational_status: 'Operational Status: OPTIMAL',
        system_ok: 'SYSTEM: OK',
        db_connected: 'DB: CONNECTED',
        save: 'Save',
        cancel: 'Cancel',
        language: 'Language',
        select_language: 'Select Language',
        spanish: 'Spanish',
        english: 'English',
        // Dashboard
        welcome: 'Welcome back!',
        total_balance: 'Total Balance',
        monthly_income: 'Monthly Income',
        monthly_expenses: 'Monthly Expenses',
        recent_movements: 'Recent Movements',
        view_all: 'View all',
        engineering_card: 'Engineering Financial Card',
        // Stats
        efficiency: 'Efficiency',
        savings_rate: 'Savings Rate',
        financial_health: 'Financial Health',
        // Engineering Assistant
        smart_timeline: 'Smart Timeline',
        next_events: 'Next Events',
        no_events: 'No upcoming events',
        financial_metrics: 'Engineering Metrics',
        // Goals
        monthly_suggested: 'Monthly suggested savings',
        progress: 'Progress',
        target_date: 'Target date',
        target_amount: 'Target Amount',
        current_amount: 'Current Amount',
        deadline: 'Deadline',
        add_goal: 'Add Goal',
        edit_goal: 'Edit Goal',
        suggested_savings: 'Suggested Savings',
        // Categories
        add_category: 'New Category',
        edit_category: 'Edit Category',
        category_name: 'Category Name',
        category_color: 'Color',
        search_categories: 'Search categories...',
        delete_confirm: 'Are you sure you want to delete this?',
        // Finance Summary
        total_income: 'Total Income',
        total_expense: 'Total Expenses',
        net_balance: 'Net Balance',
        export_csv: 'Export CSV',
        export_pdf: 'Export PDF',
        filter_month: 'This Month',
        filter_last_month: 'Last Month',
        filter_custom: 'Custom Range',
        transactions: 'Transactions',
        // Time
        morning: 'Good morning!',
        afternoon: 'Good afternoon!',
        evening: 'Good evening!',
        // Dashboard (extra)
        amount_greater_than_zero: 'Amount must be greater than 0',
        movement_registered: 'Movement registered successfully!',
        registration_error: 'Registration error. Check the fields.',
        guest: 'User',
        no_movements: 'You don\'t have any movements yet.',
        register_first: 'Register first',
        no_description: 'No description',
        quick_registration: 'Quick Registration',
        movement_type: 'Movement Type',
        expense_label: '💸 Expense',
        income_label: '💰 Income',
        amount_label: 'Amount ($)',
        description_label: 'Description',
        description_placeholder: 'E.g.: Coffee, Supermarket, Salary...',
        category_label: 'Category',
        select_category: 'Select a category...',
        date_label: 'Date',
        saving: 'Saving...',
        // ChatIA
        ai_welcome: 'Hello! I am your **AI Financial Assistant** powered by Gemini. I have access to your real financial data and can answer any questions about your income, expenses, balance, and more. How can I help you today?',
        typing: 'The assistant is thinking...',
        ask_question: 'Ask about your finances...',
        ai_error: 'Sorry, an error occurred while processing your question. Try again.',
        ai_disclaimer: 'The AI Assistant can make mistakes. Verify important data in My Finances.',
        connected_data: 'Connected to your data',
        suggestion_1: 'How much have I spent in total?',
        suggestion_2: 'What is my current balance?',
        suggestion_3: 'In which category do I spend the most?',
        suggestion_4: 'How much have I saved?',
        suggestion_5: 'What is my financial risk?',
        suggestion_6: 'How many days does my money last?',
        fallback_expense: 'Check the **"My Finances"** section to see your expense details.',
        fallback_income: 'You can see your total income in the **"My Finances"** section.',
        fallback_balance: 'Your balance is shown on the **Dashboard** at the top.',
        fallback_error: 'I couldn\'t connect to the AI Assistant. You can see all your financial data in **"My Finances"** and the **Dashboard**.',
        // Profile
        manage_info: 'Manage your personal information',
        member_since: 'Member since',
        full_name: 'Full Name',
        email_address: 'Email Address',
        change_password: 'Change Password',
        new_password: 'New Password',
        confirm_password: 'Confirm Password',
        password_min: 'Min. 6 characters',
        password_repeat: 'Repeat the password',
        passwords_dont_match: 'Passwords don\'t match',
        password_help: 'Leave both fields empty to not change the password.',
        profile_updated: 'Profile updated successfully!',
        profile_error: 'Error updating profile.',
        // Login / Register / ForgotPassword
        login_title: 'Log in to your account',
        login_button: 'Log in',
        logging_in: 'Logging in...',
        no_account: 'Don\'t have an account?',
        register_here: 'Register here',
        forgot_password_q: 'Forgot your password?',
        register_title: 'Create a new account',
        register_button: 'Register',
        creating_account: 'Creating account...',
        have_account: 'Already have an account?',
        login_here: 'Log in',
        recovery_title: 'Recover Password',
        recovery_desc: 'Enter your email and we will send you a link to reset your password.',
        recovery_email_sent: 'Email sent!',
        recovery_instr: 'We have sent a recovery link to: ',
        recovery_button: 'Send recovery link',
        sending: 'Sending...',
        back_to_login: 'Back to login',
        // EngineeringAssistant
        critical: 'CRITICAL',
        important: 'IMPORTANT',
        optional: 'OPTIONAL',
        delete_event_confirm: 'Delete this event from the timeline?',
        goal_prefix: 'Goal: ',
        expired_label: 'EXPIRED',
        today_label: 'TODAY',
        for_label: 'FOR',
        missing_amount: 'Missing ',
        to_complete: ' to complete.',
        recurrent_expense_prefix: 'Recurrent Expense: ',
        projected: 'PROJECTED',
        recurrent_suggestion: 'Recurrent expense detected. Suggestion: schedule a set-aside.',
        monthly_deficit: 'Monthly Deficit',
        alert: 'ALERT',
        overspend_desc: 'Your expenses exceed your income this month.',
        critical_buffer: 'Critical Buffer',
        low_buffer_desc: 'Buffer less than 30 days',
        remaining_days_label: 'days remaining',
        past_label: 'PAST',
        event_label: 'EVENT: ',
        manual_event_desc: 'Manual event registered by the user.',
        survival_engine: 'Survival Engine',
        safe_daily_rate: 'SAFE DAILY EXPENSE RATE',
        per_day: '/ DAY',
        buffer_time_label: 'BUFFER TIME',
        days: 'Days',
        low_risk: 'LOW',
        set_asides_month: 'Set-asides (Current Month)',
        view_movements: 'VIEW MOVEMENTS',
        no_expenses_month: 'No expenses recorded this month.',
        strategic_goals: 'Strategic Goals',
        schedule: 'SCHEDULE',
        no_active_goals: 'No active goals.',
        add_event: 'ADD EVENT',
        optimize: 'OPTIMIZE',
        schedule_manual_event: 'SCHEDULE MANUAL EVENT',
        event_title: 'Event Title',
        event_title_placeholder: 'E.g.: Rent payment, Maintenance, etc.',
        amount_optional: 'Amount (Optional)',
        priority_label: 'Priority',
        priority_important: 'IMPORTANT',
        priority_critical: 'CRITICAL / URGENT',
        priority_optional: 'OPTIONAL / REMINDER',
        add_to_timeline: 'ADD TO TIMELINE',
        vs_previous_month: 'vs previous month',
        close_notification: 'Close notification',
        category_deleted: 'Category deleted.',
        category_delete_error: 'Error deleting. The category may have associated movements.',
        category_name_required: 'Name is required.',
        category_updated: 'Category updated!',
        category_created: 'Category created!',
        category_error: 'Error saving category.',
        organize_finances: 'Organize your income & expenses',
        category_label: 'category',
        categories_label: 'categories',
        category_color: 'Category color',
        edit_label: 'Edit',
        delete_label: 'Delete',
        no_results_for: 'No results for',
        no_custom_categories: 'No custom categories',
        categories_help: 'Categories help you organize your finances',
        preview: 'Preview...',
        category_name: 'Category name',
        custom_color: 'Custom color',
        category_delete_warning: 'This may affect transactions linked to this category.',
        error_loading_goals: 'Error loading goals:',
        goal_updated: 'Goal updated!',
        goal_created: 'Goal created successfully!',
        goal_save_error: 'Error saving goal. Check the data.',
        goal_deleted: 'Goal deleted.',
        goal_delete_error: 'Error deleting goal.',
        invalid_amount: 'Enter a valid amount.',
        progress_updated: 'Progress updated!',
        progress_error: 'Error updating progress.',
        active_label: 'active',
        actives_label: 'active',
        completed_label_sm: 'completed',
        completed_labels_sm: 'completed',
        expired_label_sm: 'Expired',
        deadline_label: 'Deadline',
        goal_completed_title: 'GOAL COMPLETED',
        no_goals_yet: 'No goals yet',
        create_first_goal: 'Create first goal',
        goal_name_label: 'Goal Name',
        update_progress: 'Update Progress',
        update_button: 'Update',
        // Common
        risk_low: 'LOW',
        risk_medium: 'MEDIUM',
        risk_critical: 'CRITICAL',
        loading: 'Loading...',
        error_loading: 'Error loading data',
        no_data: 'No data available'

    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'es');

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => (prev === 'es' ? 'en' : 'es'));
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
