import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
    es: {
        dashboard: 'Dashboard',
        finances: 'Mis Finanzas',
        categories: 'Categorías',
        goals: 'Metas',
        last_movements: 'Últimos movimientos',
        all_day: 'Todo el día',
        reports: 'Análisis Patrimonial',
        strategic_analysis: 'Análisis Patrimonial',
        strategic_goals: 'Metas Estratégicas',
        wealth_evolution: 'Evolución del Patrimonio',
        monthly_comparison: 'Comparativa Mensual',
        update_progress: 'Actualizar Avance',
        cumulative_balance: 'Saldo de la Cuenta',
        budgets: 'Presupuestos',
        ai_assistant: 'Asistente IA',
        settings: 'Configuración',
        profile: 'Perfil',
        logout: 'Cerrar Sesión',
        account_type: 'Básica',
        notifications: 'Notificaciones',
        terminal_id: 'ID DE TERMINAL',
        operational_status: 'Estado Operacional: ÓPTIMO',
        system_ok: 'SISTEMA: OK',
        db_connected: 'BD: CONECTADA',
        save: 'Guardar',
        cancel: 'Cancelar',
        language: 'Idioma',
        select_language: 'Seleccionar Idioma',
        spanish: 'Español',
        english: 'Inglés',
        // Dashboard
        welcome: '¡Hola de nuevo!',
        welcome_back: '¡Bienvenido de nuevo!',
        login_error: 'Error al iniciar sesión',
        total_balance: 'Balance Total',
        liquid_balance: 'Disponible',
        goal_savings: 'Ahorro Metas',
        investments_total: 'Inversiones',
        monthly_income: 'Ingresos del Mes',
        monthly_expenses: 'Gastos del Mes',
        recent_movements: 'Movimientos Recientes',
        view_all: 'Ver todo',
        engineering_card: 'Agenda Financiera',
        smart_tracking_system: 'SISTEMA DE SEGUIMIENTO INTELIGENTE',
        budget_allocation: 'Distribución de Presupuestos',
        survival_engine: 'Motor de Supervivencia',
        safe_daily_rate: 'Tasa Higiénica de Gasto',
        per_day: 'por día',
        buffer_time_label: 'Tiempo de Amortiguación',
        financial_health: 'Salud Financiera',
        // Engineering Assistant
        smart_timeline: 'Línea de Tiempo Inteligente',
        next_events: 'Próximos Eventos',
        no_events: 'No hay eventos próximos',
        financial_metrics: 'Métricas de Ingeniería',
        monthly_reminder: 'Recordatorio Mensual',
        delete_event_confirm: '¿Eliminar este evento de la agenda?',
        recurring_event: 'Evento Recurrente',
        payment_day: 'Día de Pago',
        deadline_day: 'Día Límite',
        next_payment: 'Próximo Pago',
        deadline_approaching: '¡Límite de pago cerca!',
        delete_action: 'Eliminar',
        keep_action: 'Mantener',
        not_paid_yet: 'Aún no pagado',
        already_paid: 'Pagado este mes',
        priority_optional: 'Opcional',
        priority_important: 'Importante',
        priority_critical: 'Crítico',
        add_event: 'Añadir Evento',
        event_title: 'Título del Evento',
        event_title_placeholder: 'Ej: Cumpleaños de Mamá',
        priority_label: 'Prioridad',
        // Recordatorios & Eventos
        edit_event: 'Editar Evento',
        save_changes: 'Guardar Cambios',
        schedule_manual_event: 'Agendar Evento Manual',
        add_to_timeline: 'Añadir a Línea de Tiempo',
        monthly_suggested: 'Sugerencia de ahorro mensual',
        income: 'Ingresos',
        expenses: 'Gastos',
        balance: 'Balance',
        monthly_summary: 'Resumen del Mes',
        uncategorized: 'Sin Categoría',
        progress: 'Progreso',
        target_date: 'Fecha objetivo',
        target_amount: 'Monto Objetivo',
        current_amount: 'Monto Actual',
        deadline: 'Fecha Límite',
        add_goal: 'Agregar Meta',
        edit_goal: 'Editar Meta',
        suggested_savings: 'Ahorro Sugerido',
        // Categories
        add_category: 'Nueva Categoría',
        edit_category: 'Editar Categoría',
        category_name: 'Nombre de la Categoría',
        category_color: 'Color',
        search_categories: 'Buscar categorías...',
        delete_confirm: '¿Estás seguro de eliminar esto?',
        // Finance Summary
        total_income: 'Total Ingresos',
        total_expense: 'Total Gastos',
        net_balance: 'Balance Neto',
        savings_rate: 'tasa de ahorro',
        export_csv: 'Exportar CSV',
        export_pdf: 'Exportar PDF',
        add_movement: 'Nuevo Movimiento',
        edit_movement: 'Editar Movimiento',
        filter_month: 'Este Mes',
        filter_last_month: 'Mes Pasado',
        filter_all: 'Todos',
        filter_custom: 'Personalizado',
        transactions: 'Transacciones',
        monthly_summary_card: 'Resumen del Mes',
        monthly_savings: 'Ahorro del Mes',
        most_spent_category: 'Categoría más Gastada',
        // Time
        morning: '¡Buenos días!',
        afternoon: '¡Buenas tardes!',
        evening: '¡Buenas noches!',
        // Dashboard (extra)
        amount_greater_than_zero: 'El monto debe ser mayor a 0',
        movement_registered: '¡Movimiento registrado correctamente!',
        registration_error: 'Error al registrar. Verifica los campos.',
        guest: 'Usuario',
        no_movements: 'Aún no tienes movimientos.',
        register_first: 'Registrar primero',
        today_label: 'Hoy',
        yesterday_label: 'Ayer',
        earlier_label: 'Ayer',
        no_description: 'Sin descripción',
        quick_registration: 'Registro Rápido',
        movement_type: 'Tipo de Movimiento',
        expense_label: 'Gasto',
        income_label: 'Ingreso',
        amount_label: 'Monto ($)',
        description_label: 'Descripción',
        description_placeholder: 'Ej: Café, Supermercado, Sueldo...',
        category_label: 'Categoría',
        search_category: 'Buscar categoría...',
        no_categories_found: 'No se encontraron categorías',
        select_category: 'Selecciona una categoría',
        date_label: 'Fecha',
        saving: 'Guardando...',
        member_since: 'Miembro desde',
        min_ago: 'HACE {n} MIN',
        hours_ago: 'HACE {n} HORAS',
        days_ago: 'HACE {n} DÍAS',
        report_subtitle: 'Visión estratégica de tu salud financiera y crecimiento.',
        past_label: 'Pasado',
        manual_event_desc: 'Evento manual registrado en tu agenda.',
        event_label: 'Evento: ',
        mark_as_paid: 'Marcar como pagado',
        undo_payment: 'Deshacer pago',
        paid_label: 'PAGADO',
        projected: 'Proyectado',
        alert: 'Alerta',
        from_label: 'Desde',
        days: 'días',
        remaining_days_label: 'días restantes',
        undo: 'Deshacer',
        action_undone: 'Acción deshecha correctamente',
        overspend_desc: 'Tus gastos han superado tus ingresos este mes.',
        low_buffer_desc: 'Tu tiempo de amortiguación es peligrosamente bajo',
        // ChatIA
        ai_welcome: '¡Hola! Soy tu **Asistente Financiero IA** potenciado por Gemini. Tengo acceso a tus datos financieros reales y puedo responder cualquier pregunta sobre tus ingresos, gastos, balance y más. ¿En qué te ayudo hoy?',
        typing: 'El asistente está pensando...',
        ask_question: 'Pregunta sobre tus finanzas...',
        ai_error: 'Lo siento, ocurrió un error al procesar tu pregunta. Intenta de nuevo.',
        ai_disclaimer: 'El Asistente IA puede cometer errores. Verifica datos importantes en Mis Finanzas.',
        connected_data: 'Conectado a tus datos',
        suggestion_1: '¿Cuánto he gastado en total?',
        suggestion_2: '¿Cuál es mi balance actual?',
        suggestion_3: '¿En qué categoría gasto más?',
        suggestion_4: '¿Cuánto he ahorrado?',
        suggestion_5: '¿Cuál es mi riesgo financiero?',
        suggestion_6: '¿Cuántos días me dura el dinero?',
        fallback_expense: 'Revisa la sección **"Mis Finanzas"** para ver el detalle de tus gastos.',
        fallback_income: 'Puedes ver tus ingresos totales en la sección **"Mis Finanzas"**.',
        fallback_balance: 'Tu balance se muestra en el **Dashboard** en la parte superior.',
        fallback_error: 'No pude conectarme al Asistente IA. Puedes ver todos tus datos financieros en **"Mis Finanzas"** y el **Dashboard**.',
        // Profile
        manage_info: 'Gestiona tu información personal',
        member_since: 'Miembro desde',
        full_name: 'Nombre Completo',
        email_address: 'Correo Electrónico',
        change_password: 'Cambiar Contraseña',
        new_password: 'Nueva Contraseña',
        confirm_password: 'Confirmar Contraseña',
        password_min: 'Mín. 6 caracteres',
        password_repeat: 'Repite la contraseña',
        passwords_dont_match: 'Las contraseñas no coinciden',
        password_help: 'Deja ambos campos vacíos para no cambiar la contraseña.',
        profile_updated: '¡Perfil actualizado correctamente!',
        profile_error: 'Error al actualizar el perfil.',
        personal_details: 'Detalles Personales',
        manage_info: 'Gestiona tu información personal',
        verified_account: 'Cuenta Verificada',
        profile_completeness: 'Perfil completado al',
        full_name: 'Nombre Completo',
        email_address: 'Correo Electrónico',
        phone_number: 'Teléfono',
        bio: 'Biografía',
        phone_verified: 'Teléfono verificado',
        verified: 'Verificado',
        verify: 'Verificar',
        sms_alerts: 'Recibir alertas de seguridad vía SMS',
        ai_synced: 'Sincronizado con IA',
        ai_bio_hint: '* Tu biografía ayuda a la IA a personalizar tus consejos financieros.',
        activity_overview: 'Resumen de Actividad',
        last_sync: 'Última Sincronización',
        none: 'Ninguno',
        security_level: 'Nivel de Seguridad',
        session_history: 'Historial de Sesiones',
        active_now: 'Activo ahora',
        browser: 'Navegador',
        location: 'Ubicación',
        device: 'Dispositivo',
        last_activity: 'Última actividad',
        change_avatar: 'Personalizar Avatar',
        top_category_spent: 'Mayor gasto en',
        total_saved_all: 'Total Ahorrado',
        bio_placeholder: 'Cuéntanos sobre tus metas financieras...',
        financial_snapshot: 'Resumen Financiero',
        account_security: 'Seguridad de la Cuenta',
        security_status: 'Estado de Seguridad',
        high_level: 'Alto',
        medium_level: 'Medio',
        low_level: 'Bajo',
        // Login / Register / ForgotPassword
        login_title: 'Inicia sesión en tu cuenta',
        login_button: 'Ingresar',
        logging_in: 'Iniciando sesión...',
        no_account: '¿No tienes una cuenta?',
        register_here: 'Regístrate aquí',
        forgot_password_q: '¿Olvidaste tu contraseña?',
        register_title: 'Crea una cuenta nueva',
        register_button: 'Regístrate',
        creating_account: 'Creando cuenta...',
        have_account: '¿Ya tienes una cuenta?',
        login_here: 'Inicia sesión',
        recovery_title: 'Recuperar Contraseña',
        recovery_desc: 'Ingresa tu correo y te enviaremos un enlace para restablecer tu contraseña.',
        recovery_email_sent: '¡Correo enviado!',
        recovery_instr: 'Hemos enviado un enlace de recuperación a: ',
        recovery_button: 'Enviar enlace de recuperación',
        sending: 'Enviando...',
        back_to_login: 'Volver al inicio de sesión',
        main_navigation: 'Navegación principal',
        close_menu: 'Cerrar menú',
        open_menu: 'Abrir menú',
        // Elite Login Specific
        start_session: 'Iniciar Sesión',
        welcome_elite: 'Bienvenido',
        create_account_elite: 'Crea tu Cuenta',
        recover_elite: 'Recuperar',
        manage_future: 'Gestiona tu futuro hoy',
        join_elite: 'Únete a la elite financiera',
        forgot_pwd_q_elite: '¿Olvidaste tu contraseña?',
        register_action: 'Registrarse',
        next_step: 'Siguiente Paso',
        back_to_login_elite: 'Volver al Login',
        recover_desc_elite: 'Introduce tu correo para recibir un enlace de recuperación.',
        send_link: 'Enviar Enlace',
        interact: 'Interactuar',
        enter_full_name: 'Por favor ingresa tu nombre completo',
        enter_valid_email: 'Ingresa un correo electrónico válido',
        password_len: 'La contraseña debe tener al menos 6 caracteres',
        passwords_mismatch: 'Las contraseñas no coinciden',
        registration_err: 'Error al registrarse',
        continue_with: 'O continuar con',
        google_sign_in: 'Iniciar sesión con Google',
        account_created: '¡Cuenta creada!',
        entering_dashboard: 'Ingresando a tu panel...',
        step_1_personal: 'Paso 1 de 2 — Info Personal',
        step_2_password: 'Paso 2 de 2 — Crea tu Contraseña',
        password_field: 'Contraseña',
        confirm_password_field: 'Confirmar Contraseña',
        back_action: 'Atrás',
        create_account_action: 'Crear Cuenta',
        just_now: 'JUSTO AHORA',
        min_ago: 'HACE {n} MIN',
        hours_ago: 'HACE {n} HORAS',
        days_ago: 'HACE {n} DÍAS',
        processing_fortune: 'Procesando Fortuna',
        simulate_impact: 'Simular Impacto',
        example_day: 'Ej: {n}',
        search_description: 'Buscar descripción...',
        vs_previous_month: 'vs mes pasado',
        close_notification: 'Cerrar notificación',
        category_deleted: 'Categoría eliminada.',
        category_delete_error: 'Error al eliminar. La categoría puede tener movimientos asociados.',
        category_name_required: 'El nombre es obligatorio.',
        category_updated: '¡Categoría actualizada!',
        category_created: '¡Categoría creada!',
        custom_color: 'Color personalizado',
        category_delete_warning: 'Esto puede afectar los movimientos asociados a esta categoría.',
        error_loading_goals: 'Error cargando metas:',
        goal_updated: '¡Meta actualizada!',
        goal_created: '¡Meta creada con éxito!',
        goal_save_error: 'Error al guardar la meta. Revisa los datos.',
        goal_deleted: 'Meta eliminada.',
        goal_delete_error: 'Error al eliminar la meta.',
        invalid_amount: 'Ingresa un monto válido.',
        progress_updated: '¡Avance actualizado!',
        progress_error: 'Error al actualizar el avance.',
        active_label: 'activa',
        actives_label: 'activas',
        completed_label_sm: 'completada',
        completed_labels_sm: 'completadas',
        expired_label_sm: 'Vencida',
        deadline_label: 'Límite',
        goal_completed_title: 'META COMPLETADA',
        no_goals_yet: 'Sin metas aún',
        create_first_goal: 'Crear mi primera meta',
        goal_name_label: 'Nombre de la Meta',
        update_button: 'Actualizar',
        // Common
        risk_low: 'BAJO',
        risk_medium: 'MEDIO',
        risk_critical: 'CRÍTICO',
        export_pdf: 'Exportar PDF',
        export_csv: 'Exportar CSV',
        engineering_card: 'INGENIERÍA FINANCIERA',
        smart_tracking_system: 'SISTEMA DE RASTREO INTELIGENTE',
        survival_engine: 'MOTOR DE SUPERVIVENCIA',
        safe_daily_rate: 'TASA DIARIA SEGURA',
        per_day: '/ día',
        budget_allocation: 'ASIGNACIÓN DE PRESUPUESTO',
        strategic_goals: 'METAS ESTRATÉGICAS',
        update_progress: 'Actualizar Progreso',
        edit_goal: 'Editar Meta',
        goal_milestone_title: '¡HITOS LOGRADO!',
        goal_milestone_desc: 'Has alcanzado el {percentage}% de tu meta: {name}',
        savings_challenge_title: 'RETO DE AHORRO',
        savings_challenge_desc: 'Intenta gastar un 5% menos hoy para aumentar tu Buffer Time.',
        sub_reminder_title: 'RECORDATORIO DE SUSCRIPCIÓN',
        sub_reminder_desc: 'Pago proyectado para {name} próximamente.',
        discipline_streak_title: 'RACHA DE DISCIPLINA',
        discipline_streak_desc: 'Has mantenido tu presupuesto por {days} días seguidos. ¡Sigue así!',
        invest_alert_title: 'OPORTUNIDAD DE INVERSIÓN',
        invest_alert_desc: 'Tienes un excedente de ${amount}. Considera moverlo a una cuenta de inversión.',
        balance_forecast_title: 'PRONÓSTICO DE SALDO',
        balance_forecast_desc: 'Se proyecta un saldo final de ${amount} para el cierre de mes.',
        low_buffer_desc: 'Tu reserva de efectivo es baja',
        remaining_days_label: 'días restantes',
        simulation_mode: 'MODO SIMULACIÓN',
        if_you_cancel: 'Si cancelas el gasto de {name} (${amount}), este sería el impacto:',
        current_buffer: 'BUFFER ACTUAL',
        new_buffer: 'BUFFER NUEVO',
        positive_impact: 'IMPACTO POSITIVO',
        understood: 'ENTENDIDO',
        morning: 'Buenos días',
        afternoon: 'Buenas tardes',
        evening: 'Buenas noches',
        show_balances: 'Mostrar saldos',
        hide_balances: 'Ocultar saldos',
        of_the_month: 'del mes',
        pdf_hash: 'HASH DE INTEGRIDAD',
        pdf_summary_title: 'RESUMEN EJECUTIVO DE BIENESTAR',
        pdf_net_balance: 'BALANCE NETO MENSUAL',
        pdf_footer_msg: 'Este reporte fue generado automáticamente por LanaTrix. La información es estrictamente confidencial.',
        pdf_page_cert: 'Página certificada por el Auditor IQ',
        loading: 'Cargando...',
        error_loading: 'Error al cargar los datos',
        no_data: 'No hay datos disponibles',
        // Reports
        key_metrics: 'Métricas Clave',
        net_balance_report: 'Balance Neto',
        projected_savings: 'Ahorro Proyectado',
        reserve_days: 'Días de Reserva',
        expenses_by_category: 'Gastos por Categoría',
        cash_flow_evolution: 'Evolución de Flujo',
        max_income: 'Ingreso Máximo',
        max_expense: 'Gasto Máximo',
        daily_avg: 'Promedio Diario',
        risk_level_label: 'Nivel de Riesgo',
        no_expenses_recorded: 'Sin gastos registrados',
        movement_history: 'Historial de Movimientos',
        movement_trend: 'Tendencia de Movimientos',
        income_vs_expense_day: 'Ingresos vs Gastos por Día',
        expense_distribution: 'Distribución de Gastos',
        reports_subtitle: "Análisis técnico de tus movimientos",
        executive_summary: "RESUMEN EJECUTIVO DE CARTERA",
        daily_burn_rate: "TASA DE QUEMADO DIARIO",
        // PDF / Exports
        pdf_report_title: 'Reporte Financiero',
        pdf_generated_at: 'Generado el',
        // pdf_summary_title: 'Resumen del Período', // Duplicate, handled above
        percentage_label: '% DEL TOTAL DE GASTOS',
        // pdf_net_balance: 'Balance Neto', // Duplicate, handled above
        total_balance: 'Balance Total',
        total_balance_desc: 'Resta histórica de todos tus ingresos menos todos tus gastos registrados.',
        monthly_income: 'Ingresos Mensuales',
        monthly_income_desc: 'Suma de todos tus ingresos registrados en el mes actual.',
        monthly_expenses: 'Gastos Mensuales',
        monthly_expenses_desc: 'Suma de todos tus gastos registrados en el mes actual.',
        liquid_balance: 'Disponibilidad Líquida',
        liquid_balance_desc: 'Tu balance total menos lo que tienes reservado para Metas de Ahorro e Inversiones.',
        pdf_income: 'Ingresos Totales',
        pdf_expense: 'Gastos Totales',
        pdf_negative: '(Negativo)',
        pdf_movements_title: 'Movimientos Detallados',
        pdf_page: 'Página',
        pdf_of: 'de',
        pdf_footer: 'LanaTrix Core - Reporte de Inteligencia Financiera',
        generating_pdf: 'Generando PDF...',
        exporting_tx: 'Exportando movimientos...',
        no_tx_export: 'No hay transacciones para exportar',
        // Presupuestos
        // of_the_month: 'del Mes', // Duplicate, handled above
        budget_saved: 'Presupuesto guardado',
        save_error: 'Error al guardar',
        delete_budget_confirm: '¿Eliminar este límite de presupuesto?',
        budget_deleted: 'Presupuesto eliminado',
        delete_error: 'Error al eliminar',
        configuring_limits: 'Configurando límites financieros...',
        control_spending: 'Controla cuánto quieres gastar por categoría cada mes',
        global_budget: 'Presupuesto Global (Mensual)',
        available: 'Disponible',
        budget_alert: 'ALERTA: Has superado el 90% de tu presupuesto este mes.',
        define_limit: 'Definir Límite',
        select_placeholder: 'Seleccionar...',
        monthly_limit_label: 'Límite Mensual ($)',
        assign_limit: 'ASIGNAR LÍMITE',
        budget_help: 'Los presupuestos te ayudan a no gastar de más. Recibirás alertas visuales cuando te acerques al límite.',
        no_budgets_title: 'Aún no has definido límites mensuales.',
        no_budgets_subtitle: 'Empieza seleccionando una categoría a la izquierda.',
        limit_prefix: 'Límite: ',
        spent_prefix: 'Gastado: ',
        // Configuracion
        lang_changed_en: 'Idioma cambiado a Inglés',
        lang_changed_es: 'Idioma cambiado a Español',
        settings_desc: 'Gestiona tus preferencias de cuenta y aplicación.',
        security: 'Seguridad',
        lang_help: '* Cambiar el idioma afectará a todos los menús y etiquetas principales de la aplicación.',
        dark_mode: 'Modo Oscuro',
        light_mode: 'Modo Claro',
        appearance: 'Apariencia',
        // Categorias
        movement_updated: 'Movimiento actualizado',
        // Seguridad y Notificaciones
        password_current: 'Contraseña Actual',
        password_new: 'Nueva Contraseña',
        password_confirm: 'Confirmar Contraseña',
        password_changed: 'Contraseña actualizada correctamente',
        notif_budget_exceed: 'Alertas de límite de presupuesto',
        notif_new_login: 'Alertas de nuevos inicios de sesión',
        notif_weekly_report: 'Resumen semanal por correo',
        notif_ai_tips: 'Consejos de ahorro de la IA',
        notif_updated: 'Preferencias de notificación actualizadas',
        no_notifications: 'No hay notificaciones pendientes',
        clear_all: 'Limpiar todo',
        recent_activity: 'Actividad Reciente',
        // Evolución Línea de Tiempo
        // goal_milestone_title: 'HITO DE META ALCANZADO', // Duplicate, handled above
        // goal_milestone_desc: 'Has alcanzado el {percentage}% de tu meta: {name}. ¡Sigue así!', // Duplicate, handled above
        // savings_challenge_title: 'RETO DE FIN DE SEMANA', // Duplicate, handled above
        // savings_challenge_desc: 'Mantén tus gastos hormiga en $0 por las próximas 48 horas.', // Duplicate, handled above
        // sub_reminder_title: 'SUSCRIPCIÓN PRÓXIMA', // Duplicate, handled above
        // sub_reminder_desc: 'Se detectó un cargo recurrente para {name} en los próximos días.', // Duplicate, handled above
        // discipline_streak_title: 'RACHA DE DISCIPLINA', // Duplicate, handled above
        // discipline_streak_desc: 'Has estado bajo tu presupuesto diario por {days} días seguidos. 🏆', // Duplicate, handled above
        // invest_alert_title: 'OPORTUNIDAD DE INVERSIÓN', // Duplicate, handled above
        // invest_alert_desc: 'Tu balance es sólido. Considera mover ${amount} a tu fondo de ahorro/inv.ersión.', // Duplicate, handled above
        // balance_forecast_title: 'PRONÓSTICO DE CIERRE', // Duplicate, handled above
        // balance_forecast_desc: 'Saldo proyectado al final del mes: ${amount}.', // Duplicate, handled above
        days_streak: 'días',
        hide_challenges: 'Ocultar Retos de Ahorro',
        hide_forecasts: 'Ocultar Pronóstico Mensual',
        timeline_settings: 'Ajustes de Línea de Tiempo',
        show_challenges: 'Mostrar retos de ahorro sugeridos por la IA',
        show_forecasts: 'Mostrar proyecciones de saldo a fin de mes',
        expenses_section: 'Gastos',
        income_section: 'Ingresos',
        category_type: 'Tipo de Categoría',
        system_category_no_edit: 'Esta categoría es del sistema y no se puede modificar.',
        starting_system: 'Iniciando Sistema...',
        organize_finances: 'Organiza y visualiza tus ingresos y gastos',
        no_custom_categories: 'Sin categorizar',
        no_category: 'Sin Categoría',
        delete_warning: 'Esta acción no se puede deshacer.',
        pdf_subtitle: 'SISTEMA TRANSACCIONAL PATRIMONIAL',
        // pdf_hash: 'HASH DE INTEGRIDAD', // Duplicate, handled above
        // pdf_footer_msg: 'REPORTE GENERADO MEDIANTE PROTOCOLO ELITE LANATRIX', // Duplicate, handled above
        // pdf_page_cert: 'CERTIFICADO DIGITAL PAG', // Duplicate, handled above
        pdf_filename_prefix: 'AUDITORIA_ELITE_',
        pdf_audit_title: 'AUDITORÍA',
        csv_filename_prefix: 'AUDITORIA_',
        actions_label: 'Acciones',
        edit_label: 'Editar',
        delete_label: 'Eliminar',
        search_placeholder: 'Buscar...',
        clear_search: 'Limpiar búsqueda',
        no_results_search: 'No hay resultados para la búsqueda',
        period_label: 'Período:',
        to_label: 'Hasta',
        register_to_see: 'Registra un gasto para visualizar',
        no_expenses_cat: 'No hay gastos registrados en este período',
        movement_deleted: 'Movimiento eliminado correctamente',
        filter_week: 'Últimos 7 días',
        filter_30_days: 'Últimos 30 días',

        // Balance y Visibilidad
        // hide_balances: 'Ocultar saldos', // Duplicate, handled above
        // show_balances: 'Mostrar saldos', // Duplicate, handled above

        // Simulación (Engineering Assistant)
        // simulation_mode: 'Modo Simulación', // Duplicate, handled above
        // if_you_cancel: 'Si cancelaras {name} ({amount}):', // Duplicate, handled above
        // current_buffer: 'Buffer Actual', // Duplicate, handled above
        // new_buffer: 'Nuevo Buffer', // Duplicate, handled above
        // positive_impact: 'Impacto Positivo:', // Duplicate, handled above
        // understood: 'Entendido', // Duplicate, handled above

        // Gráficos
        total_label: 'Total',
        evolution_label: 'Evolución',
        comparative_label: 'Comparativa',
        distribution_label: 'Distribución',
        system_label: 'Sistema',
        no_categories_yet: 'No hay categorías de {type} todavía',
        monthly_suffix: '/mes',
        expenses_lower: 'gastos',
        income_lower: 'ingresos',
        monthly_suggested_short: 'Ahorro sugerido',
        pdf_platform_subtitle: 'PLATAFORMA DE GESTIÓN PATRIMONIAL ELITE',
        pdf_report_id: 'ID DE REPORTE',
        pdf_auditor_iq_title: 'AUDITOR IQ: POTENCIAL DEDUCIBLE',
        pdf_auditor_iq_msg: 'He identificado ${amount} en gastos que podrían ser deducibles de impuestos.',
        pdf_confidentiality: 'CONFIDENCIALIDAD NIVEL 4 | LANATRIX DIGITAL ASSET MANAGEMENT',
        pdf_page_prefix: 'PÁGINA',
        pdf_of_suffix: 'DE',
        health_label: 'Salud',
        education_label: 'Educación',
        investments_label: 'Inversiones',
        profile_updated: 'Perfil actualizado correctamente',
        profile_error: 'Error al actualizar el perfil',
        verified_account: 'Cuenta Verificada',
        member_since: 'Miembro desde',
        profile_completeness: 'Completitud del Perfil',
        personal_details: 'Datos Personales',
        manage_info: 'Gestiona tu información básica y preferencias',
        full_name: 'Nombre Completo',
        email_address: 'Correo Electrónico',
        phone_number: 'Teléfono',
        bio: 'Biografía / Nota Personal',
        bio_placeholder: 'Escribe algo sobre ti o tus metas financieras...',
        saving: 'Guardando...',
        top_category_spent: 'Categoría Mayor Gasto',
        security_level: 'Nivel de Seguridad',
        high_level: 'Alto',
        account_security: 'Seguridad de la Cuenta',
        active_now: 'Activa ahora',
        security_status: 'Estado de Seguridad',
        activity_overview: 'Resumen de Actividad',
        min_ago: 'hace {n} min',
        account_type_elite: 'Elite',
        account_type_basic: 'Básico',
        not_paid_yet: 'No pagado aún',
        next_payment: 'Próximo pago',
        deadline_approaching: 'Plazo cercano',
        past_label: 'Pasado',
        paid_label: 'Pagado',
        deadline_day: 'Día Límite',
        example_day: 'Ej: {n}',
        add_to_timeline: 'Agregar a Línea de Tiempo',
        save_changes: 'Guardar Cambios',
        schedule_manual_event: 'Programar Evento Manual',
        event_title: 'Título del Evento',
        event_title_placeholder: 'Ej: Renta, Seguro, etc.',
        recurring_event: 'Evento Recurrente',
        monthly_reminder: 'Recordatorio Mensual',
        delete_event_confirm: '¿Eliminar este evento?',
        keep_action: 'Mantener',
        delete_action: 'Eliminar',
        simulate_impact: 'Simular Impacto',
        mark_as_paid: 'Marcar como Pagado',
        undo_payment: 'Deshacer Pago',
        event_label: 'Evento: ',
        manual_event_desc: 'Evento manual programado en tu agenda estratégica.',
        overspend_desc: 'Tus gastos del mes superan tus ingresos. Revisa tus prioridades.',
        critical_buffer: 'BUFFER CRÍTICO',
        low_buffer_desc: 'Tu reserva de efectivo es baja',
        remaining_days_label: 'días restantes',
        morning: 'Buenos días',
        afternoon: 'Buenas tardes',
        evening: 'Buenas noches',
        show_balances: 'Mostrar saldos',
        hide_balances: 'Ocultar saldos',
        of_the_month: 'del mes',
        pdf_hash: 'HASH DE INTEGRIDAD',
        pdf_summary_title: 'RESUMEN EJECUTIVO DE BIENESTAR',
        pdf_net_balance: 'BALANCE NETO MENSUAL',
        pdf_footer_msg: 'Este reporte fue generado automáticamente por LanaTrix. La información es estrictamente confidencial.',
        pdf_page_cert: 'Página certificada por el Auditor IQ',
        upload_avatar: 'Subir Imagen',
        uploading: 'Subiendo...',
        avatar_updated: 'Avatar actualizado',
        upload_error: 'Error al subir imagen',
        change_password: 'Cambiar Contraseña',
        current_password: 'Contraseña Actual',
        new_password: 'Nueva Contraseña',
        confirm_password: 'Confirmar Contraseña',
        passwords_dont_match: 'Las contraseñas no coinciden',
        password_changed_success: 'Contraseña actualizada con éxito',
        password_change_error: 'Error al actualizar la contraseña',
        no_activity: 'Sin actividad reciente',
        activity_overview: 'Resumen de Actividad',
        last_sync: 'Última Sincronización',
        min_ago: 'hace {n} min',
        top_category_spent: 'Categoría con más gasto',
        security_level: 'Nivel de Seguridad',
        high_level: 'Alto',
        account_security: 'Seguridad de la Cuenta',
        active_now: 'Activo ahora',
        yesterday_label: 'Ayer',
        security_status: 'Estado de Seguridad',
        account_security_desc: 'Actualiza tus credenciales para mantener tu cuenta segura.',
    },
    en: {
        dashboard: 'Dashboard',
        finances: 'My Finances',
        categories: 'Categories',
        goals: 'Goals',
        last_movements: 'Last movements',
        all_day: 'All day',
        reports: 'Wealth Analysis',
        strategic_analysis: 'Wealth Analysis',
        strategic_goals: 'Strategic Goals',
        wealth_evolution: 'Wealth Evolution',
        monthly_comparison: 'Monthly Comparison',
        update_progress: 'Update Progress',
        cumulative_balance: 'Account Balance',
        budgets: 'Budgets',
        ai_assistant: 'AI Assistant',
        settings: 'Settings',
        profile: 'Profile',
        logout: 'Logout',
        account_type: 'Basic',
        notifications: 'Notifications',
        terminal_id: 'TERMINAL ID',
        operational_status: 'Operational Status: OPTIMAL',
        system_ok: 'SYSTEM: OK',
        db_connected: 'DB: CONNECTED',
        save: 'Save',
        cancel: 'Cancel',
        language: 'Language',
        select_language: 'Select Language',
        spanish: 'Spanish',
        english: 'English',
        // Dashboard
        welcome: 'Welcome back!',
        welcome_back: 'Welcome back!',
        login_error: 'Error logging in',
        total_balance: 'Total Balance',
        liquid_balance: 'Available',
        goal_savings: 'Goal Savings',
        total_balance_desc: 'Historical sum of all your income minus all your registered expenses.',
        monthly_income: 'Monthly Income',
        monthly_income_desc: 'Sum of all your income registered in the current month.',
        monthly_expenses: 'Monthly Expenses',
        monthly_expenses_desc: 'Sum of all your expenses registered in the current month.',
        // liquid_balance: 'Liquid Availability', // Duplicate, handled above
        liquid_balance_desc: 'Your total balance minus what you have reserved for Savings Goals and Investments.',
        investments_total: 'Investments',
        // monthly_income: 'Monthly Income', // Duplicate, handled above
        // monthly_expenses: 'Monthly Expenses', // Duplicate, handled above
        recent_movements: 'Recent Movements',
        view_all: 'View all',
        engineering_card: 'Financial Agenda',
        smart_tracking_system: 'SMART TRACKING SYSTEM',
        budget_allocation: 'Budget Allocation',
        survival_engine: 'Survival Engine',
        safe_daily_rate: 'Safe Daily Spending Rate',
        per_day: 'per day',
        buffer_time_label: 'Buffer Time',
        financial_health: 'Financial Health',
        // Engineering Assistant
        smart_timeline: 'Smart Timeline',
        next_events: 'Next Events',
        no_events: 'No upcoming events',
        financial_metrics: 'Engineering Metrics',
        monthly_reminder: 'Monthly Reminder',
        days: 'days',
        delete_event_confirm: 'Delete this event from the agenda?',
        recurring_event: 'Recurring Event',
        payment_day: 'Payment Day',
        deadline_day: 'Deadline Day',
        next_payment: 'Next Payment',
        deadline_approaching: 'Deadline approaching!',
        delete_action: 'Delete',
        keep_action: 'Keep',
        not_paid_yet: 'Not paid yet',
        already_paid: 'Paid this month',
        priority_optional: 'Optional',
        priority_important: 'Important',
        priority_critical: 'Critical',
        add_event: 'Add Event',
        event_title: 'Event Title',
        event_title_placeholder: 'E.g., Mom\'s Birthday',
        priority_label: 'Priority',
        // Recordatorios & Eventos
        edit_event: 'Edit Event',
        save_changes: 'Save Changes',
        schedule_manual_event: 'Schedule Manual Event',
        add_to_timeline: 'Add to Timeline',
        monthly_suggested: 'Monthly suggested savings',
        income: 'Income',
        expenses: 'Expenses',
        balance: 'Balance',
        monthly_summary: 'Monthly Summary',
        uncategorized: 'Uncategorized',
        progress: 'Progress',
        target_date: 'Target date',
        target_amount: 'Target Amount',
        current_amount: 'Current Amount',
        deadline: 'Deadline',
        add_goal: 'Add Goal',
        edit_goal: 'Edit Goal',
        suggested_savings: 'Suggested Savings',
        // Categories
        add_category: 'New Category',
        edit_category: 'Edit Category',
        category_name: 'Category Name',
        category_color: 'Color',
        search_categories: 'Search categories...',
        delete_confirm: 'Are you sure you want to delete this?',
        // Finance Summary
        total_income: 'Total Income',
        total_expense: 'Total Expenses',
        net_balance: 'Net Balance',
        savings_rate: 'savings rate',
        export_csv: 'Export CSV',
        add_movement: 'New Movement',
        edit_movement: 'Edit Movement',
        filter_month: 'This Month',
        filter_last_month: 'Last Month',
        filter_all: 'All',
        filter_custom: 'Custom Range',
        transactions: 'Transactions',
        monthly_summary_card: 'Monthly Summary',
        monthly_savings: 'Monthly Savings',
        most_spent_category: 'Most Spent Category',
        // Time
        morning: 'Good morning!',
        afternoon: 'Good afternoon!',
        evening: 'Good evening!',
        // Dashboard (extra)
        amount_greater_than_zero: 'Amount must be greater than 0',
        movement_registered: 'Movement registered successfully!',
        registration_error: 'Registration error. Check the fields.',
        guest: 'User',
        no_movements: 'You don\'t have any movements yet.',
        register_first: 'Register first',
        today_label: 'Today',
        yesterday_label: 'Yesterday',
        earlier_label: 'Yesterday',
        no_description: 'No description',
        quick_registration: 'Quick Registration',
        movement_type: 'Movement Type',
        expense_label: 'Expense',
        income_label: 'Income',
        amount_label: 'Amount ($)',
        description_label: 'Description',
        description_placeholder: 'E.g.: Coffee, Supermarket, Salary...',
        category_label: 'Category',
        search_category: 'Search category...',
        no_categories_found: 'No categories found',
        select_category: 'Select a category',
        date_label: 'Date',
        saving: 'Saving...',
        report_subtitle: 'Strategic vision of your financial health and growth.',
        past_label: 'Past',
        manual_event_desc: 'Manual event registered in your agenda.',
        event_label: 'Event: ',
        mark_as_paid: 'Mark as paid',
        undo_payment: 'Undo payment',
        paid_label: 'PAID',
        projected: 'Projected',
        alert: 'Alert',
        from_label: 'From',
        remaining_days_label: 'remaining days',
        overspend_desc: 'Your expenses have exceeded your income this month.',
        low_buffer_desc: 'Your buffer time is dangerously low',
        // ChatIA
        ai_welcome: 'Hello! I am your **AI Financial Assistant** powered by Gemini. I have access to your real financial data and can answer any questions about your income, expenses, balance, and more. How can I help you today?',
        typing: 'The assistant is thinking...',
        ask_question: 'Ask about your finances...',
        ai_error: 'Sorry, an error occurred while processing your question. Try again.',
        ai_disclaimer: 'The AI Assistant can make mistakes. Verify important data in My Finances.',
        connected_data: 'Connected to your data',
        suggestion_1: 'How much have I spent in total?',
        suggestion_2: 'What is my current balance?',
        suggestion_3: 'In which category do I spend the most?',
        suggestion_4: 'How much have I saved?',
        suggestion_5: 'What is my financial risk?',
        suggestion_6: 'How many days does my money last?',
        fallback_expense: 'Check the **"My Finances"** section to see your expense details.',
        fallback_income: 'You can see your total income in the **"My Finances"** section.',
        fallback_balance: 'Your balance is shown on the **Dashboard** at the top.',
        fallback_error: 'I couldn\'t connect to the AI Assistant. You can see all your financial data in **"My Finances"** and the **Dashboard**.',
        // Profile
        manage_info: 'Manage your personal information',
        member_since: 'Member since',
        full_name: 'Full Name',
        email_address: 'Email Address',
        change_password: 'Change Password',
        new_password: 'New Password',
        confirm_password: 'Confirm Password',
        password_min: 'Min. 6 characters',
        password_repeat: 'Repeat the password',
        passwords_dont_match: 'Passwords don\'t match',
        password_help: 'Leave both fields empty to not change the password.',
        profile_updated: 'Profile updated successfully!',
        profile_error: 'Error updating profile.',
        // Login / Register / ForgotPassword
        login_title: 'Log in to your account',
        login_button: 'Log in',
        logging_in: 'Logging in...',
        no_account: 'Don\'t have an account?',
        register_here: 'Register here',
        forgot_password_q: 'Forgot your password?',
        register_title: 'Create a new account',
        register_button: 'Register',
        creating_account: 'Creating account...',
        have_account: 'Already have an account?',
        login_here: 'Log in',
        recovery_title: 'Recover Password',
        recovery_desc: 'Enter your email and we will send you a link to reset your password.',
        recovery_email_sent: 'Email sent!',
        recovery_instr: 'We have sent a recovery link to: ',
        recovery_button: 'Send recovery link',
        sending: 'Sending...',
        back_to_login: 'Back to login',
        main_navigation: 'Main navigation',
        close_menu: 'Close menu',
        open_menu: 'Open menu',
        // Elite Login Specific
        start_session: 'Start Session',
        welcome_elite: 'Welcome',
        create_account_elite: 'Create Account',
        recover_elite: 'Recover',
        manage_future: 'Manage your future today',
        join_elite: 'Join the financial elite',
        forgot_pwd_q_elite: 'Forgot your password?',
        register_action: 'Register',
        next_step: 'Next Step',
        back_to_login_elite: 'Back to Login',
        recover_desc_elite: 'Enter your email to receive a recovery link.',
        send_link: 'Send Link',
        interact: 'Interact',
        enter_full_name: 'Please enter your full name',
        enter_valid_email: 'Enter a valid email address',
        password_len: 'Password must be at least 6 characters',
        passwords_mismatch: 'Passwords do not match',
        registration_err: 'Registration error',
        continue_with: 'Or continue with',
        google_sign_in: 'Sign in with Google',
        account_created: 'Account created!',
        entering_dashboard: 'Entering your dashboard...',
        step_1_personal: 'Step 1 of 2 — Personal Info',
        step_2_password: 'Step 2 of 2 — Set Password',
        password_field: 'Password',
        confirm_password_field: 'Confirm Password',
        back_action: 'Back',
        create_account_action: 'Create Account',
        just_now: 'JUST NOW',
        min_ago: '{n} MIN AGO',
        hours_ago: '{n} HOURS AGO',
        days_ago: '{n} DAYS AGO',
        processing_fortune: 'Processing Fortune',
        simulate_impact: 'Simulate Impact',
        example_day: 'Eg: {n}',
        search_description: 'Search description...',
        vs_previous_month: 'vs previous month',
        close_notification: 'Close notification',
        category_deleted: 'Category deleted.',
        category_delete_error: 'Error deleting. The category may have associated movements.',
        category_name_required: 'Name is required.',
        category_updated: 'Category updated!',
        category_created: 'Category created!',
        category_error: 'Error saving category.',
        error_loading_goals: 'Error loading goals:',
        goal_updated: 'Goal updated!',
        goal_created: 'Goal created successfully!',
        goal_save_error: 'Error saving goal. Check the data.',
        goal_deleted: 'Goal deleted.',
        goal_delete_error: 'Error deleting goal.',
        invalid_amount: 'Enter a valid amount.',
        progress_updated: 'Progress updated!',
        progress_error: 'Error updating progress.',
        active_label: 'active',
        actives_label: 'active',
        completed_label_sm: 'completed',
        completed_labels_sm: 'completed',
        expired_label_sm: 'Expired',
        deadline_label: 'Deadline',
        goal_completed_title: 'GOAL COMPLETED',
        no_goals_yet: 'No goals yet',
        create_first_goal: 'Create first goal',
        goal_name_label: 'Goal Name',
        update_button: 'Update',
        // Common
        risk_low: 'LOW',
        risk_medium: 'MEDIUM',
        risk_critical: 'CRITICAL',
        export_pdf: 'Export PDF',
        export_csv: 'Export CSV',
        engineering_card: 'FINANCIAL ENGINEERING',
        smart_tracking_system: 'SMART TRACKING SYSTEM',
        survival_engine: 'SURVIVAL ENGINE',
        safe_daily_rate: 'SAFE DAILY RATE',
        per_day: '/ day',
        budget_allocation: 'BUDGET ALLOCATION',
        strategic_goals: 'STRATEGIC GOALS',
        update_progress: 'Update Progress',
        edit_goal: 'Edit Goal',
        goal_milestone_title: 'MILESTONE ACHIEVED!',
        goal_milestone_desc: 'You have reached {percentage}% of your goal: {name}',
        savings_challenge_title: 'SAVINGS CHALLENGE',
        savings_challenge_desc: 'Try spending 5% less today to increase your Buffer Time.',
        sub_reminder_title: 'SUBSCRIPTION REMINDER',
        sub_reminder_desc: 'Projected payment for {name} coming up.',
        discipline_streak_title: 'DISCIPLINE STREAK',
        discipline_streak_desc: 'You have maintained your budget for {days} days straight. Keep it up!',
        invest_alert_title: 'INVESTMENT OPPORTUNITY',
        invest_alert_desc: 'You have a surplus of ${amount}. Consider moving it to an investment account.',
        balance_forecast_title: 'BALANCE FORECAST',
        balance_forecast_desc: 'A final balance of ${amount} is projected for the end of the month.',
        low_buffer_desc: 'Your cash reserve is low',
        remaining_days_label: 'remaining days',
        simulation_mode: 'SIMULATION MODE',
        if_you_cancel: 'If you cancel the expense for {name} (${amount}), this would be the impact:',
        current_buffer: 'CURRENT BUFFER',
        new_buffer: 'NEW BUFFER',
        positive_impact: 'POSITIVE IMPACT',
        understood: 'UNDERSTOOD',
        morning: 'Good morning',
        afternoon: 'Good afternoon',
        evening: 'Good evening',
        show_balances: 'Show balances',
        hide_balances: 'Hide balances',
        of_the_month: 'of the month',
        pdf_hash: 'INTEGRITY HASH',
        pdf_summary_title: 'EXECUTIVE WELLNESS SUMMARY',
        pdf_net_balance: 'MONTHLY NET BALANCE',
        pdf_footer_msg: 'This report was automatically generated by LanaTrix. Information is strictly confidential.',
        pdf_page_cert: 'Page certified by Auditor IQ',
        loading: 'Loading...',
        error_loading: 'Error loading data',
        no_data: 'No data available',
        // Reports
        key_metrics: 'Key Metrics',
        net_balance_report: 'Net Balance',
        projected_savings: 'Projected Savings',
        reserve_days: 'Reserve Days',
        expenses_by_category: 'Expenses by Category',
        cash_flow_evolution: 'Cash Flow Evolution',
        max_income: 'Max Income',
        max_expense: 'Max Expense',
        daily_avg: 'Daily Avg',
        risk_level_label: 'Risk Level',
        no_expenses_recorded: 'No expenses recorded',
        movement_history: 'Movement History',
        movement_trend: 'Movement Trend',
        income_vs_expense_day: 'Income vs Expense per Day',
        expense_distribution: 'Expense Distribution',
        reports_subtitle: "Technical analysis of your movements",
        executive_summary: "EXECUTIVE PORTFOLIO SUMMARY",
        daily_burn_rate: "DAILY BURN RATE",
        // PDF / Exports
        export_pdf: "Export PDF",
        percentage_label: '% OF TOTAL EXPENSES',
        budget_saved: 'Budget saved',
        save_error: 'Error saving',
        delete_budget_confirm: 'Delete this budget limit?',
        budget_deleted: 'Budget deleted',
        delete_error: 'Error deleting',
        configuring_limits: 'Configuring financial limits...',
        control_spending: 'Control how much you want to spend per category each month',
        global_budget: 'Global Budget (Monthly)',
        available: 'Available',
        budget_alert: 'ALERT: You have exceeded 90% of your budget this month.',
        define_limit: 'Define Limit',
        select_placeholder: 'Select...',
        monthly_limit_label: 'Monthly Limit ($)',
        assign_limit: 'ASSIGN LIMIT',
        budget_help: 'Budgets help you avoid overspending. You will receive visual alerts when you approach the limit.',
        no_budgets_title: 'No monthly limits defined yet.',
        no_budgets_subtitle: 'Start by selecting a category on the left.',
        limit_prefix: 'Limit: ',
        spent_prefix: 'Spent: ',
        // Configuracion
        lang_changed_en: 'Language changed to English',
        lang_changed_es: 'Idioma cambiado a Español',
        settings_desc: 'Manage your account and application preferences.',
        security: 'Security',
        lang_help: '* Changing the language will affect all major menus and labels of the application.',
        dark_mode: 'Dark Mode',
        light_mode: 'Light Mode',
        appearance: 'Appearance',
        // Categorias
        movement_updated: 'Movement updated',
        // Security & Notifications
        password_current: 'Current Password',
        password_new: 'New Password',
        password_confirm: 'Confirm Password',
        password_changed: 'Password updated successfully',
        notif_budget_exceed: 'Budget limit alerts',
        notif_new_login: 'New login alerts',
        notif_weekly_report: 'Weekly email summary',
        notif_ai_tips: 'AI saving tips',
        notif_updated: 'Notification preferences updated',
        no_notifications: 'No pending notifications',
        clear_all: 'Clear all',
        recent_activity: 'Recent Activity',
        // Profile
        personal_details: 'Personal Details',
        financial_snapshot: 'Financial Snapshot',
        account_security: 'Account Security',
        phone_number: 'Phone Number',
        bio: 'Bio',
        phone_verified: 'Phone verified',
        verified: 'Verified',
        verify: 'Verify',
        sms_alerts: 'Receive security alerts via SMS',
        ai_synced: 'AI Synced',
        ai_bio_hint: '* Your biography helps the AI personalize your financial advice.',
        verified_account: 'Verified Account',
        security_status: 'Security Status',
        high: 'High',
        medium: 'Medium',
        low_label: 'Low',
        last_sync: 'Last Sync',
        activity_overview: 'Activity Overview',
        security_level: 'Security Level',
        session_history: 'Session History',
        active_now: 'Active now',
        browser: 'Browser',
        location: 'Location',
        device: 'Device',
        last_activity: 'Last activity',
        change_avatar: 'Customize Avatar',
        profile_completeness: 'Profile completeness',
        top_category_spent: 'Top spending in',
        total_saved_all: 'Total Saved',
        bio_placeholder: 'Tell us about your financial goals...',
        high_level: 'High',
        medium_level: 'Medium',
        low_level: 'Low',
        security_status: 'Security Status',
        // Timeline Evolution
        goal_milestone_title: 'GOAL MILESTONE REACHED',
        goal_milestone_desc: 'You have reached {percentage}% of your goal: {name}. Keep going!',
        savings_challenge_title: 'WEEKEND CHALLENGE',
        savings_challenge_desc: 'Keep your impulse spending at $0 for the next 48 hours.',
        sub_reminder_title: 'UPCOMING SUBSCRIPTION',
        sub_reminder_desc: 'A recurring charge for {name} was detected in the coming days.',
        discipline_streak_title: 'DISCIPLINE STREAK',
        discipline_streak_desc: 'You have been under your daily budget for {days} days straight. 🏆',
        invest_alert_title: 'INVESTMENT OPPORTUNITY',
        invest_alert_desc: 'Your balance is solid. Consider moving ${amount} to your savings/investment fund.',
        balance_forecast_title: 'MONTH-END FORECAST',
        balance_forecast_desc: 'Projected balance at the end of the month: ${amount}.',
        days_streak: 'days',
        hide_challenges: 'Hide Savings Challenges',
        hide_forecasts: 'Hide Monthly Forecast',
        timeline_settings: 'Timeline Settings',
        show_challenges: 'Show AI-suggested savings challenges',
        show_forecasts: 'Show month-end balance projections',
        expenses_section: 'Expenses',
        income_section: 'Income',
        category_type: 'Category Type',
        system_category_no_edit: 'This is a system category and cannot be modified.',
        starting_system: 'Starting System...',
        organize_finances: 'Organize and visualize your income and expenses',
        no_custom_categories: 'Uncategorized',
        no_category: 'No Category',
        delete_warning: 'This action cannot be undone.',
        pdf_subtitle: 'TRANSACTIONAL WEALTH SYSTEM',
        pdf_hash: 'INTEGRITY HASH',
        pdf_footer_msg: 'REPORT GENERATED VIA LANATRIX ELITE PROTOCOL',
        pdf_page_cert: 'DIGITAL CERTIFICATE PAG',
        pdf_filename_prefix: 'ELITE_AUDIT_',
        pdf_audit_title: 'AUDIT',
        csv_filename_prefix: 'AUDIT_',
        actions_label: 'Actions',
        edit_label: 'Edit',
        delete_label: 'Delete',
        search_placeholder: 'Search...',
        clear_search: 'Clear search',
        no_results_search: 'No results found',
        period_label: 'Period:',
        to_label: 'To',
        register_to_see: 'Register an expense to see data',
        no_expenses_cat: 'No expenses recorded in this period',
        movement_deleted: 'Movement deleted successfully',
        filter_week: 'Last 7 days',
        filter_30_days: 'Last 30 days',

        // Balance and Visibility
        hide_balances: 'Hide balances',
        show_balances: 'Show balances',

        // Simulation (Engineering Assistant)
        simulation_mode: 'Simulation Mode',
        if_you_cancel: 'If you cancel {name} ({amount}):',
        current_buffer: 'Current Buffer',
        new_buffer: 'New Buffer',
        positive_impact: 'Positive Impact:',
        understood: 'Understood',

        // Charts
        total_label: 'Total',
        evolution_label: 'Evolution',
        comparative_label: 'Comparative',
        distribution_label: 'Distribution',
        system_label: 'System',
        no_categories_yet: 'No {type} categories yet',
        monthly_suffix: '/mo',
        expenses_lower: 'expenses',
        income_lower: 'income',
        monthly_suggested_short: 'Suggested savings',
        pdf_platform_subtitle: 'ELITE WEALTH MANAGEMENT PLATFORM',
        pdf_report_id: 'REPORT ID',
        pdf_auditor_iq_title: 'AUDITOR IQ: POTENTIAL DEDUCTIBLE',
        pdf_auditor_iq_msg: 'I have identified ${amount} in expenses that could be tax-deductible.',
        pdf_confidentiality: 'LEVEL 4 CONFIDENTIALITY | LANATRIX DIGITAL ASSET MANAGEMENT',
        pdf_page_prefix: 'PAGE',
        pdf_of_suffix: 'OF',
        health_label: 'Health',
        education_label: 'Education',
        investments_label: 'Investments',
        profile_updated: 'Profile updated successfully',
        profile_error: 'Error updating profile',
        verified_account: 'Verified Account',
        member_since: 'Member since',
        profile_completeness: 'Profile Completeness',
        personal_details: 'Personal Details',
        manage_info: 'Manage your personal information and preferences',
        full_name: 'Full Name',
        email_address: 'Email Address',
        phone_number: 'Phone Number',
        bio: 'Biography / Personal Note',
        phone_verified: 'Phone verified',
        verified: 'Verified',
        verify: 'Verify',
        sms_alerts: 'Receive security alerts via SMS',
        ai_synced: 'AI Synced',
        ai_bio_hint: '* Your biography helps the AI personalize your financial advice.',
        bio_placeholder: 'Write something about yourself or your financial goals...',
        saving: 'Saving...',
        top_category_spent: 'Top Spending Category',
        security_level: 'Security Level',
        high_level: 'High',
        account_security: 'Account Security',
        active_now: 'Active now',
        security_status: 'Security Status',
        activity_overview: 'Activity Overview',
        min_ago: '{n} min ago',
        account_type_elite: 'Elite',
        account_type_basic: 'Basic',
        not_paid_yet: 'Not paid yet',
        next_payment: 'Next payment',
        deadline_approaching: 'Deadline approaching',
        past_label: 'Past',
        paid_label: 'Paid',
        deadline_day: 'Deadline Day',
        example_day: 'Ex: {n}',
        add_to_timeline: 'Add to Timeline',
        save_changes: 'Save Changes',
        schedule_manual_event: 'Schedule Manual Event',
        event_title: 'Event Title',
        event_title_placeholder: 'Ex: Rent, Insurance, etc.',
        recurring_event: 'Recurring Event',
        monthly_reminder: 'Monthly Reminder',
        delete_event_confirm: 'Delete this event?',
        keep_action: 'Keep',
        delete_action: 'Delete',
        simulate_impact: 'Simulate Impact',
        mark_as_paid: 'Mark as Paid',
        undo_payment: 'Undo Payment',
        event_label: 'Event: ',
        manual_event_desc: 'Manual event scheduled in your strategic agenda.',
        overspend_desc: 'Your monthly expenses exceed your income. Review your priorities.',
        critical_buffer: 'CRITICAL BUFFER',
        low_buffer_desc: 'Your cash reserve is low',
        remaining_days_label: 'remaining days',
        morning: 'Good morning',
        afternoon: 'Good afternoon',
        evening: 'Good evening',
        show_balances: 'Show balances',
        hide_balances: 'Hide balances',
        of_the_month: 'of the month',
        pdf_hash: 'INTEGRITY HASH',
        pdf_summary_title: 'EXECUTIVE WELLNESS SUMMARY',
        pdf_net_balance: 'MONTHLY NET BALANCE',
        pdf_footer_msg: 'This report was automatically generated by LanaTrix. The information is strictly confidential.',
        pdf_page_cert: 'Page certified by Auditor IQ',
        upload_avatar: 'Upload Image',
        uploading: 'Uploading...',
        avatar_updated: 'Avatar updated',
        upload_error: 'Error uploading image',
        change_password: 'Change Password',
        current_password: 'Current Password',
        new_password: 'New Password',
        confirm_password: 'Confirm Password',
        passwords_dont_match: 'Passwords do not match',
        password_changed_success: 'Password updated successfully',
        password_change_error: 'Error updating password',
        no_activity: 'No recent activity',
        activity_overview: 'Activity Overview',
        last_sync: 'Last Sync',
        min_ago: '{n} min ago',
        top_category_spent: 'Top category spent',
        security_level: 'Security Level',
        high_level: 'High',
        account_security: 'Account Security',
        active_now: 'Active now',
        yesterday_label: 'Yesterday',
        security_status: 'Security Status',
        account_security_desc: 'Update your credentials to keep your account secure.',
    }
};

export const LanguageProvider = ({ children }) => {
    const [language, setLanguage] = useState(localStorage.getItem('language') || 'es');

    useEffect(() => {
        localStorage.setItem('language', language);
    }, [language]);

    const t = (key) => {
        return translations[language][key] || key;
    };

    const toggleLanguage = () => {
        setLanguage(prev => (prev === 'es' ? 'en' : 'es'));
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t, toggleLanguage }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
